// GENERATED by apps-script/build-runtime.mjs — DO NOT EDIT.
// Sources: transport/asc-link.mjs, core/asc-core.mjs, adapters/github/github-adapter.mjs, adapters/github/github-rest-client.mjs, receipts/write-receipt.mjs, flow/confirm-sync.mjs, receipts/History.gs
// Regenerate: node apps-script/build-runtime.mjs

// ==== verbatim: receipts/History.gs ====
const HISTORY_WRITER_CONFIG = Object.freeze({
  spreadsheetId: '11pWE0E-jEZhigVAYGcsfVXW0TODRcNMgOZHFfUQIHKw',
  sheetName: 'HISTORY'
});

const HISTORY_WRITER_HEADERS = Object.freeze([
  'request_id',
  'project_id',
  'operation',
  'destination',
  'status',
  'affected_resource',
  'commit_or_record_id',
  'source_commit',
  'timestamp',
  'failure_reason',
  'receipt_json'
]);

function appendHistory(historyEntry) {
  const validation = validateHistoryEntry_(historyEntry);
  if (!validation.valid) {
    return {
      ok: false,
      outcome: 'HISTORY_WRITE_FAILED',
      error: {
        code: 'INVALID_HISTORY_ENTRY',
        message: validation.errors.join('; ')
      }
    };
  }

  try {
    const sheet = SpreadsheetApp
      .openById(HISTORY_WRITER_CONFIG.spreadsheetId)
      .getSheetByName(HISTORY_WRITER_CONFIG.sheetName);

    if (!sheet) {
      return {
        ok: false,
        outcome: 'HISTORY_WRITE_FAILED',
        error: { code: 'HISTORY_SHEET_MISSING', message: 'HISTORY sheet is missing.' }
      };
    }

    const headers = sheet
      .getRange(1, 1, 1, HISTORY_WRITER_HEADERS.length)
      .getValues()[0];

    if (!HISTORY_WRITER_HEADERS.every(function (header, index) {
      return headers[index] === header;
    })) {
      return {
        ok: false,
        outcome: 'HISTORY_WRITE_FAILED',
        error: { code: 'HISTORY_HEADER_MISMATCH', message: 'HISTORY headers do not match.' }
      };
    }

    const row = HISTORY_WRITER_HEADERS.map(function (header) {
      return historyEntry[header];
    });
    sheet.appendRow(row);

    return {
      ok: true,
      outcome: 'HISTORY_PERSISTED',
      rowNumber: sheet.getLastRow()
    };
  } catch (error) {
    return {
      ok: false,
      outcome: 'HISTORY_WRITE_FAILED',
      error: { code: 'HISTORY_WRITER_EXCEPTION', message: 'HISTORY writer failed.' }
    };
  }
}

function validateHistoryEntry_(historyEntry) {
  const errors = [];
  const requiredStrings = [
    'request_id',
    'project_id',
    'operation',
    'timestamp',
    'receipt_json'
  ];

  if (!historyEntry || typeof historyEntry !== 'object') {
    return { valid: false, errors: ['History entry must be an object.'] };
  }

  requiredStrings.forEach(function (field) {
    if (typeof historyEntry[field] !== 'string' || historyEntry[field].length === 0) {
      errors.push(field + ' must be a non-empty string');
    }
  });

  if (historyEntry.status !== 'SUCCESS' && historyEntry.status !== 'FAILED') {
    errors.push('status must be SUCCESS or FAILED');
  }

  return { valid: errors.length === 0, errors: errors };
}

// ==== bundled ES modules (lazy, namespaced) ====
var ASC_RUNTIME_CACHE_ = null;

function ascRuntime_() {
  if (ASC_RUNTIME_CACHE_) {
    return ASC_RUNTIME_CACHE_;
  }
  const shims = ascRuntimeShims_();
  const ASC_NS = {};
  // ---- module: transport/asc-link.mjs ----
  ASC_NS.transport = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const ASC_FRAGMENT_KEY = "asc";
    const ENVELOPE_VERSION = "0.1";

    function utf8ToBase64Url(text) {
      const bytes = new TextEncoder().encode(text);
      let binary = "";
      for (const byte of bytes) binary += String.fromCharCode(byte);
      return btoa(binary)
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=+$/g, "");
    }

    function base64UrlToUtf8(value) {
      if (!/^[A-Za-z0-9_-]+$/.test(value)) {
        throw new Error("ASC fragment payload is not valid Base64URL.");
      }

      const padded = value
        .replace(/-/g, "+")
        .replace(/_/g, "/")
        .padEnd(Math.ceil(value.length / 4) * 4, "=");

      const binary = atob(padded);
      const bytes = Uint8Array.from(binary, ch => ch.charCodeAt(0));
      return new TextDecoder().decode(bytes);
    }

    function createEnvelope(contract, options = {}) {
      if (!contract || typeof contract !== "object" || Array.isArray(contract)) {
        throw new Error("contract must be a JSON object.");
      }

      const requestId = String(options.requestId ?? "").trim();
      const expiresAt = String(options.expiresAt ?? "").trim();

      if (!requestId) throw new Error("requestId is required.");
      if (!expiresAt || Number.isNaN(Date.parse(expiresAt))) {
        throw new Error("expiresAt must be a valid date-time string.");
      }

      return {
        envelope_version: ENVELOPE_VERSION,
        request_id: requestId,
        expires_at: expiresAt,
        integrity: {
          algorithm: "SHA-256",
          digest: options.integrityDigest ?? null
        },
        contract
      };
    }

    function encodeEnvelope(envelope) {
      if (!envelope || typeof envelope !== "object" || Array.isArray(envelope)) {
        throw new Error("envelope must be a JSON object.");
      }
      return utf8ToBase64Url(JSON.stringify(envelope));
    }

    function decodeEnvelope(encodedPayload) {
      const json = base64UrlToUtf8(encodedPayload);
      const envelope = JSON.parse(json);

      if (envelope?.envelope_version !== ENVELOPE_VERSION) {
        throw new Error("Unsupported ASC envelope version.");
      }

      return envelope;
    }

    function buildAscLink(baseUrl, envelope) {
      const url = new URL(baseUrl);
      url.hash = "";
      url.searchParams.delete(ASC_FRAGMENT_KEY);

      const encoded = encodeEnvelope(envelope);
      url.hash = `${ASC_FRAGMENT_KEY}=${encoded}`;
      return url.toString();
    }

    function decodeAscLink(link) {
      const url = new URL(link);

      if (url.searchParams.has(ASC_FRAGMENT_KEY)) {
        throw new Error("ASC payload must not be carried in ordinary query parameters.");
      }

      const fragment = url.hash.startsWith("#") ? url.hash.slice(1) : url.hash;
      const prefix = `${ASC_FRAGMENT_KEY}=`;

      if (!fragment.startsWith(prefix)) {
        throw new Error("ASC fragment payload is missing.");
      }

      const encoded = fragment.slice(prefix.length);
      if (!encoded) throw new Error("ASC fragment payload is empty.");

      return decodeEnvelope(encoded);
    }

    const ASC_LINK_CONSTANTS = Object.freeze({
      fragmentKey: ASC_FRAGMENT_KEY,
      envelopeVersion: ENVELOPE_VERSION
    });

    return Object.freeze({ createEnvelope, encodeEnvelope, decodeEnvelope, buildAscLink, decodeAscLink, ASC_LINK_CONSTANTS });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: core/asc-core.mjs ----
  ASC_NS.core = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const CONTRACT_FIELDS = Object.freeze([
      'Project',
      'Source method',
      'Operation',
      'Record type',
      'Record ID',
      'Content/change',
      'Lineage',
      'Destination'
    ]);

    const DESTINATION_ADAPTERS = Object.freeze({
      GitHub: 'github',
      ASC_DB: 'asc_db'
    });

    function cloneSemanticValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneSemanticValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneSemanticValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function hasUniqueStrings(values) {
      return values.every(isNonEmptyString) && new Set(values).size === values.length;
    }

    function validationError(code, field, message) {
      return { code, field, message };
    }

    function validateContract(contract) {
      const errors = [];

      if (contract === null || typeof contract !== 'object' || Array.isArray(contract)) {
        return {
          valid: false,
          errors: [validationError('INVALID_TYPE', null, 'Contract must be an object.')]
        };
      }

      const actualFields = Object.keys(contract);
      const expectedFields = new Set(CONTRACT_FIELDS);

      CONTRACT_FIELDS.forEach(function (field) {
        if (!Object.prototype.hasOwnProperty.call(contract, field)) {
          errors.push(validationError('MISSING_FIELD', field, 'Required field is missing.'));
        }
      });

      actualFields.forEach(function (field) {
        if (!expectedFields.has(field)) {
          errors.push(validationError('EXTRA_FIELD', field, 'Top-level field is not allowed.'));
        }
      });

      ['Project', 'Source method', 'Operation', 'Record type', 'Record ID'].forEach(function (field) {
        if (Object.prototype.hasOwnProperty.call(contract, field) && !isNonEmptyString(contract[field])) {
          errors.push(validationError('INVALID_STRING', field, 'Value must be a non-empty string.'));
        }
      });

      if (Object.prototype.hasOwnProperty.call(contract, 'Content/change')) {
        const content = contract['Content/change'];
        const validContent = isNonEmptyString(content) ||
          Array.isArray(content) ||
          (content !== null && typeof content === 'object');

        if (!validContent) {
          errors.push(validationError(
            'INVALID_CONTENT',
            'Content/change',
            'Value must be an object, array, or non-empty string.'
          ));
        }
      }

      if (Object.prototype.hasOwnProperty.call(contract, 'Lineage')) {
        if (!Array.isArray(contract.Lineage)) {
          errors.push(validationError('INVALID_ARRAY', 'Lineage', 'Value must be an array.'));
        } else if (!hasUniqueStrings(contract.Lineage)) {
          errors.push(validationError(
            'INVALID_LINEAGE',
            'Lineage',
            'Items must be unique non-empty strings.'
          ));
        }
      }

      if (Object.prototype.hasOwnProperty.call(contract, 'Destination')) {
        if (!Array.isArray(contract.Destination) || contract.Destination.length === 0) {
          errors.push(validationError(
            'INVALID_DESTINATION',
            'Destination',
            'Value must contain at least one destination.'
          ));
        } else if (!hasUniqueStrings(contract.Destination)) {
          errors.push(validationError(
            'INVALID_DESTINATION',
            'Destination',
            'Items must be unique non-empty strings.'
          ));
        }
      }

      return {
        valid: errors.length === 0,
        errors
      };
    }

    function authorizeRequest(contract, authorizationContext, authorizationPolicy) {
      if (typeof authorizationPolicy !== 'function') {
        return {
          authorized: false,
          errors: [{ code: 'AUTHORIZATION_POLICY_REQUIRED', message: 'Authorization policy is required.' }]
        };
      }

      let decision;
      try {
        decision = authorizationPolicy(
          cloneSemanticValue(contract),
          authorizationContext
        );
      } catch (error) {
        return {
          authorized: false,
          errors: [{ code: 'AUTHORIZATION_POLICY_ERROR', message: 'Authorization policy failed.' }]
        };
      }

      if (!decision || decision.authorized !== true) {
        return {
          authorized: false,
          errors: [{ code: 'AUTHORIZATION_DENIED', message: 'Authorization policy did not authorize the request.' }]
        };
      }

      return {
        authorized: true,
        errors: []
      };
    }

    function routeDestinations(contract) {
      const routes = [];

      for (const destination of contract.Destination) {
        const adapterId = DESTINATION_ADAPTERS[destination];
        if (!adapterId) {
          return {
            routed: false,
            routes: [],
            error: {
              code: 'UNSUPPORTED_DESTINATION',
              destination,
              message: 'Destination is not supported by this Core proof.'
            }
          };
        }

        routes.push({ destination, adapterId });
      }

      return {
        routed: true,
        routes,
        error: null
      };
    }

    function createAdapterInvocation(contract, route) {
      return {
        destination: route.destination,
        adapterId: route.adapterId,
        contract: cloneSemanticValue(contract)
      };
    }

    function createReceiptLayerHandoff(adapterResult) {
      return {
        kind: 'ADAPTER_RESULT_TO_RECEIPT_LAYER',
        adapterResult: cloneSemanticValue(adapterResult)
      };
    }

    function processCoreRequest({
      contract,
      authorizationContext,
      authorizationPolicy
    }) {
      const validation = validateContract(contract);

      if (!validation.valid) {
        return {
          status: 'REJECTED',
          stage: 'VALIDATION',
          validation
        };
      }

      const authorization = authorizeRequest(
        contract,
        authorizationContext,
        authorizationPolicy
      );

      if (!authorization.authorized) {
        return {
          status: 'REJECTED',
          stage: 'AUTHORIZATION',
          validation,
          authorization
        };
      }

      const preservedContract = cloneSemanticValue(contract);
      const routing = routeDestinations(preservedContract);

      if (!routing.routed) {
        return {
          status: 'REJECTED',
          stage: 'ROUTING',
          validation,
          authorization,
          routing,
          contract: preservedContract
        };
      }

      const adapterInvocations = routing.routes.map(function (route) {
        return createAdapterInvocation(preservedContract, route);
      });

      return {
        status: 'ACCEPTED',
        stage: 'CORE_BOUNDARY',
        validation,
        authorization,
        contract: preservedContract,
        routes: routing.routes,
        adapterInvocations,
        receiptLayerHandoff: {
          kind: 'ADAPTER_RESULTS_PENDING_RECEIPT_LAYER',
          adapterResults: []
        }
      };
    }

    return Object.freeze({ validateContract, authorizeRequest, routeDestinations, createAdapterInvocation, createReceiptLayerHandoff, processCoreRequest });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: adapters/github/github-adapter.mjs ----
  ASC_NS.githubAdapter = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const INVOCATION_FIELDS = Object.freeze(['destination', 'adapterId', 'contract']);
    const WRITE_SPEC_FIELDS = Object.freeze([
      'repository',
      'path',
      'branch',
      'content',
      'commitMessage'
    ]);

    function cloneValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function errorResult(code, message, field) {
      return { code, message, ...(field ? { field } : {}) };
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function hasOnlyFields(value, fields) {
      return Object.keys(value).every(function (key) {
        return fields.includes(key);
      });
    }

    function validateGitHubInvocation(invocation) {
      const errors = [];

      if (invocation === null || typeof invocation !== 'object' || Array.isArray(invocation)) {
        return {
          valid: false,
          errors: [errorResult('INVALID_INVOCATION', 'Invocation must be an object.')]
        };
      }

      if (invocation.destination !== 'GitHub') {
        errors.push(errorResult('INVALID_DESTINATION', 'Invocation destination must be GitHub.', 'destination'));
      }

      if (invocation.adapterId !== 'github') {
        errors.push(errorResult('INVALID_ADAPTER', 'Invocation adapterId must be github.', 'adapterId'));
      }

      if (invocation.contract === null || typeof invocation.contract !== 'object' || Array.isArray(invocation.contract)) {
        errors.push(errorResult('INVALID_CONTRACT', 'Invocation contract must be an object.', 'contract'));
      }

      return { valid: errors.length === 0, errors };
    }

    function validateGitHubWriteSpec(writeSpec) {
      const errors = [];

      if (writeSpec === null || typeof writeSpec !== 'object' || Array.isArray(writeSpec)) {
        return {
          valid: false,
          errors: [errorResult('INVALID_WRITE_SPEC', 'Write spec must be an object.')]
        };
      }

      if (!hasOnlyFields(writeSpec, WRITE_SPEC_FIELDS)) {
        errors.push(errorResult('EXTRA_WRITE_SPEC_FIELD', 'Write spec contains an unsupported field.'));
      }

      ['repository', 'path', 'branch', 'commitMessage'].forEach(function (field) {
        if (!isNonEmptyString(writeSpec[field])) {
          errors.push(errorResult('INVALID_WRITE_SPEC_FIELD', 'Write spec field must be a non-empty string.', field));
        }
      });

      if (typeof writeSpec.content !== 'string') {
        errors.push(errorResult('INVALID_WRITE_SPEC_FIELD', 'Write spec content must be a string.', 'content'));
      }

      return { valid: errors.length === 0, errors };
    }

    function invalidInputResult(validation, writeSpecValidation) {
      return {
        outcome: 'INVALID_INPUT',
        writePerformed: false,
        verified: false,
        validation,
        writeSpecValidation
      };
    }

    function clientError(code, message) {
      return {
        ok: false,
        error: errorResult(code, message)
      };
    }

    async function callClient(method, input) {
      try {
        return await method(cloneValue(input));
      } catch (error) {
        return clientError('CLIENT_EXCEPTION', 'Injected GitHub client call failed.');
      }
    }

    function isValidReadResult(readResult) {
      if (!readResult || typeof readResult !== 'object' || typeof readResult.ok !== 'boolean') {
        return false;
      }

      if (!readResult.ok || typeof readResult.found !== 'boolean') {
        return false;
      }

      if (!readResult.found) {
        return readResult.sha === null && readResult.content === null;
      }

      return isNonEmptyString(readResult.sha) && typeof readResult.content === 'string';
    }

    function readFailure(readResult, code, message) {
      return {
        outcome: 'READ_ERROR',
        writePerformed: false,
        verified: false,
        error: cloneValue(readResult && readResult.error) || errorResult(
          code || 'READ_ERROR',
          message || 'GitHub read failed.'
        )
      };
    }

    function writeUnverifiedResult(writeSpec, commitSha, contentSha, persistedSha, error) {
      return {
        outcome: 'WRITE_UNVERIFIED',
        adapterId: 'github',
        destination: 'GitHub',
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch,
        writePerformed: true,
        commitSha,
        contentSha,
        persistedSha,
        verified: false,
        error: cloneValue(error)
      };
    }

    function isValidWriteResult(writeResult) {
      return writeResult !== null &&
        typeof writeResult === 'object' &&
        typeof writeResult.ok === 'boolean' &&
        (!writeResult.ok || isNonEmptyString(writeResult.commitSha));
    }

    async function runGitHubAdapter(invocation, writeSpec, githubClient) {
      const validation = validateGitHubInvocation(invocation);
      const writeSpecValidation = validateGitHubWriteSpec(writeSpec);

      if (!validation.valid || !writeSpecValidation.valid) {
        return invalidInputResult(validation, writeSpecValidation);
      }

      if (!githubClient || typeof githubClient.readFile !== 'function' || typeof githubClient.writeFile !== 'function') {
        return invalidInputResult(
          validation,
          {
            valid: false,
            errors: [errorResult('INVALID_CLIENT', 'Injected GitHub client must expose readFile and writeFile.')]
          }
        );
      }

      const readInput = {
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch
      };
      const currentRead = await callClient(githubClient.readFile.bind(githubClient), readInput);

      if (!currentRead || currentRead.ok !== true) {
        return readFailure(currentRead || clientError('READ_ERROR', 'GitHub read failed.'));
      }

      if (!isValidReadResult(currentRead)) {
        return readFailure(
          currentRead,
          'MALFORMED_READ_RESULT',
          'GitHub read result was malformed.'
        );
      }

      if (currentRead.found === true && currentRead.content === writeSpec.content) {
        return {
          outcome: 'NO_CHANGE',
          adapterId: 'github',
          destination: 'GitHub',
          repository: writeSpec.repository,
          path: writeSpec.path,
          branch: writeSpec.branch,
          writePerformed: false,
          commitSha: null,
          existingSha: currentRead.sha || null,
          contentSha: currentRead.sha || null,
          verified: true
        };
      }

      const writeInput = {
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch,
        content: writeSpec.content,
        commitMessage: writeSpec.commitMessage
      };

      if (currentRead.found === true) {
        if (!isNonEmptyString(currentRead.sha)) {
          return readFailure(
            currentRead,
            'MISSING_CURRENT_SHA',
            'Existing GitHub file did not provide a current SHA.'
          );
        }
        writeInput.sha = currentRead.sha;
      }

      const writeResult = await callClient(githubClient.writeFile.bind(githubClient), writeInput);

      if (!writeResult || writeResult.ok !== true) {
        return {
          outcome: 'WRITE_ERROR',
          adapterId: 'github',
          destination: 'GitHub',
          repository: writeSpec.repository,
          path: writeSpec.path,
          branch: writeSpec.branch,
          writePerformed: false,
          commitSha: writeResult && writeResult.commitSha ? writeResult.commitSha : null,
          verified: false,
          error: cloneValue(writeResult && writeResult.error) || errorResult('WRITE_ERROR', 'GitHub write failed.')
        };
      }

      const commitSha = isNonEmptyString(writeResult.commitSha) ? writeResult.commitSha : null;
      const writeResponseValid = isValidWriteResult(writeResult);
      const persistedRead = await callClient(githubClient.readFile.bind(githubClient), readInput);

      if (!persistedRead || persistedRead.ok !== true) {
        return writeUnverifiedResult(
          writeSpec,
          commitSha,
          null,
          null,
          cloneValue(persistedRead && persistedRead.error) || errorResult('VERIFY_READ_ERROR', 'Persisted-state read failed.')
        );
      }

      if (!isValidReadResult(persistedRead)) {
        return writeUnverifiedResult(
          writeSpec,
          commitSha,
          null,
          null,
          errorResult('MALFORMED_VERIFY_RESULT', 'Persisted-state read result was malformed.')
        );
      }

      if (!writeResponseValid || persistedRead.found !== true || persistedRead.content !== writeSpec.content) {
        return writeUnverifiedResult(
          writeSpec,
          commitSha,
          null,
          persistedRead.sha,
          errorResult('CONTENT_MISMATCH', 'Persisted content or write response did not verify the proposed write.')
        );
      }

      return {
        outcome: 'VERIFIED_WRITE',
        adapterId: 'github',
        destination: 'GitHub',
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch,
        writePerformed: true,
        commitSha,
        contentSha: persistedRead.sha,
        persistedSha: persistedRead.sha,
        verified: true
      };
    }

    return Object.freeze({ validateGitHubInvocation, validateGitHubWriteSpec, runGitHubAdapter });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: adapters/github/github-rest-client.mjs ----
  ASC_NS.githubRest = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const API_ROOT = 'https://api.github.com';
    const API_HEADERS = Object.freeze({
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'AISYNC-T006B-GitHub-REST-Client'
    });

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function errorResult(code, message, status) {
      return {
        ok: false,
        error: {
          code,
          message,
          ...(typeof status === 'number' ? { status } : {})
        }
      };
    }

    function validateRepository(repository) {
      return typeof repository === 'string' && /^[^/\s]+\/[^/\s]+$/.test(repository);
    }

    function validateReadInput(input) {
      if (!input || !validateRepository(input.repository)) {
        return errorResult('INVALID_REPOSITORY', 'Repository must use owner/repository form.');
      }

      if (!isNonEmptyString(input.path)) {
        return errorResult('INVALID_PATH', 'Path must be a non-empty string.');
      }

      if (!isNonEmptyString(input.branch)) {
        return errorResult('INVALID_BRANCH', 'Branch must be a non-empty string.');
      }

      return null;
    }

    function validateWriteInput(input) {
      const readError = validateReadInput(input);
      if (readError) {
        return readError;
      }

      if (typeof input.content !== 'string') {
        return errorResult('INVALID_CONTENT', 'Content must be a string.');
      }

      if (!isNonEmptyString(input.commitMessage)) {
        return errorResult('INVALID_COMMIT_MESSAGE', 'Commit message must be a non-empty string.');
      }

      if (Object.prototype.hasOwnProperty.call(input, 'sha') && !isNonEmptyString(input.sha)) {
        return errorResult('INVALID_SHA', 'SHA must be a non-empty string when supplied.');
      }

      return null;
    }

    function buildFileUrl(input) {
      const encodedPath = input.path
        .split('/')
        .map(encodeURIComponent)
        .join('/');

      return API_ROOT + '/repos/' + input.repository + '/contents/' + encodedPath +
        '?ref=' + encodeURIComponent(input.branch);
    }

    function createHeaders(token) {
      return {
        ...API_HEADERS,
        Authorization: 'Bearer ' + token
      };
    }

    async function readJson(response) {
      try {
        return await response.json();
      } catch (error) {
        return null;
      }
    }

    function decodeBase64Utf8(value) {
      if (typeof value !== 'string') {
        throw new Error('Base64 content is not a string.');
      }

      const compact = value.replace(/\s/g, '');
      if (!compact || compact.length % 4 === 1 || !/^[A-Za-z0-9+/]*={0,2}$/.test(compact)) {
        throw new Error('Base64 content is malformed.');
      }

      const paddingIndex = compact.indexOf('=');
      if (paddingIndex >= 0 && paddingIndex < compact.length - 2) {
        throw new Error('Base64 padding is malformed.');
      }

      const bytes = Buffer.from(compact, 'base64');
      const canonical = bytes.toString('base64').replace(/=+$/, '');
      if (canonical !== compact.replace(/=+$/, '')) {
        throw new Error('Base64 content is malformed.');
      }

      return bytes.toString('utf8');
    }

    function validateConfig(token, fetchImpl) {
      if (!isNonEmptyString(token)) {
        return errorResult('MISSING_TOKEN', 'GitHub token configuration is missing.');
      }

      if (typeof fetchImpl !== 'function') {
        return errorResult('MISSING_FETCH', 'Fetch implementation is missing.');
      }

      return null;
    }

    function fetchFailure(errorCode, message) {
      return errorResult(errorCode, message);
    }

    function createGitHubRestClient({ token, fetchImpl = globalThis.fetch } = {}) {
      const configError = validateConfig(token, fetchImpl);

      async function readFile(input) {
        const inputError = configError || validateReadInput(input);
        if (inputError) {
          return inputError;
        }

        try {
          const response = await fetchImpl(buildFileUrl(input), {
            method: 'GET',
            headers: createHeaders(token)
          });

          if (response.status === 404) {
            return { ok: true, found: false, sha: null, content: null };
          }

          if (response.status < 200 || response.status >= 300) {
            return errorResult('GITHUB_READ_FAILED', 'GitHub read request failed.', response.status);
          }

          const data = await readJson(response);
          if (!data || data.type !== 'file' || !isNonEmptyString(data.sha) || typeof data.content !== 'string') {
            return errorResult('MALFORMED_READ_RESPONSE', 'GitHub read response was not a valid file.');
          }

          let content;
          try {
            content = decodeBase64Utf8(data.content);
          } catch (error) {
            return errorResult('MALFORMED_FILE_CONTENT', 'GitHub file content was not valid Base64.');
          }

          return {
            ok: true,
            found: true,
            sha: data.sha,
            content
          };
        } catch (error) {
          return fetchFailure('GITHUB_FETCH_ERROR', 'GitHub request could not be completed.');
        }
      }

      async function writeFile(input) {
        const inputError = configError || validateWriteInput(input);
        if (inputError) {
          return inputError;
        }

        const body = {
          message: input.commitMessage,
          content: Buffer.from(input.content, 'utf8').toString('base64'),
          branch: input.branch
        };

        if (Object.prototype.hasOwnProperty.call(input, 'sha')) {
          body.sha = input.sha;
        }

        try {
          const response = await fetchImpl(buildFileUrl(input), {
            method: 'PUT',
            headers: createHeaders(token),
            body: JSON.stringify(body)
          });

          if (response.status < 200 || response.status >= 300) {
            return errorResult('GITHUB_WRITE_FAILED', 'GitHub write request failed.', response.status);
          }

          const data = await readJson(response);
          if (!data || !data.commit || !isNonEmptyString(data.commit.sha) ||
            !data.content || !isNonEmptyString(data.content.sha)) {
            return errorResult('MALFORMED_WRITE_RESPONSE', 'GitHub write response lacked valid identifiers.');
          }

          return {
            ok: true,
            commitSha: data.commit.sha,
            contentSha: data.content.sha
          };
        } catch (error) {
          return fetchFailure('GITHUB_FETCH_ERROR', 'GitHub request could not be completed.');
        }
      }

      return { readFile, writeFile };
    }

    return Object.freeze({ createGitHubRestClient });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: receipts/write-receipt.mjs ----
  ASC_NS.receipts = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const SUCCESS_OUTCOMES = new Set(['VERIFIED_WRITE', 'NO_CHANGE']);
    const FAILURE_OUTCOMES = new Set([
      'READ_ERROR',
      'WRITE_ERROR',
      'WRITE_UNVERIFIED',
      'INVALID_INPUT'
    ]);
    const HISTORY_FIELDS = Object.freeze([
      'request_id',
      'project_id',
      'operation',
      'destination',
      'status',
      'affected_resource',
      'commit_or_record_id',
      'source_commit',
      'timestamp',
      'failure_reason',
      'receipt_json'
    ]);

    function cloneValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function invalidResult(errors) {
      return {
        ok: false,
        outcome: 'INVALID_RECEIPT_INPUT',
        errors
      };
    }

    function validateReceiptInput(input) {
      const errors = [];

      if (!input || typeof input !== 'object') {
        return invalidResult([{ code: 'INVALID_INPUT', message: 'Receipt input must be an object.' }]);
      }

      ['requestId', 'projectId', 'operation', 'timestamp'].forEach(function (field) {
        if (!isNonEmptyString(input[field])) {
          errors.push({ code: 'INVALID_' + field.toUpperCase(), message: field + ' must be a non-empty string.' });
        }
      });

      const adapterResult = input.adapterResult;
      if (!adapterResult || typeof adapterResult !== 'object') {
        errors.push({ code: 'INVALID_ADAPTER_RESULT', message: 'Adapter result is required.' });
      } else if (!SUCCESS_OUTCOMES.has(adapterResult.outcome) && !FAILURE_OUTCOMES.has(adapterResult.outcome)) {
        errors.push({ code: 'UNKNOWN_ADAPTER_OUTCOME', message: 'Adapter outcome is not recognized.' });
      }

      return errors.length === 0 ? null : invalidResult(errors);
    }

    function affectedResource(adapterResult) {
      if (isNonEmptyString(adapterResult.repository) && isNonEmptyString(adapterResult.path)) {
        return adapterResult.repository + '/' + adapterResult.path;
      }

      return null;
    }

    function failureReason(adapterResult) {
      if (adapterResult.error && isNonEmptyString(adapterResult.error.message)) {
        return adapterResult.error.message;
      }

      if (adapterResult.outcome === 'WRITE_UNVERIFIED') {
        return 'Adapter write was not verified as persisted.';
      }

      return adapterResult.outcome;
    }

    function buildReceipt(input) {
      const adapterResult = cloneValue(input.adapterResult);
      const status = SUCCESS_OUTCOMES.has(adapterResult.outcome) ? 'SUCCESS' : 'FAILED';
      const receipt = {
        receipt_version: '0.1',
        request_id: input.requestId,
        project_id: input.projectId,
        operation: input.operation,
        destination: adapterResult.destination || null,
        status,
        affected_resource: affectedResource(adapterResult),
        commit_or_record_id: adapterResult.commitSha || null,
        source_commit: input.sourceCommit || null,
        timestamp: input.timestamp,
        failure_reason: status === 'FAILED' ? failureReason(adapterResult) : null,
        adapter_outcome: adapterResult.outcome,
        write_performed: adapterResult.writePerformed === true,
        verified: adapterResult.verified === true
      };

      return receipt;
    }

    function createWriteReceipt(input) {
      const validation = validateReceiptInput(input);
      if (validation) {
        return validation;
      }

      const receipt = buildReceipt(input);
      return {
        ok: true,
        outcome: 'RECEIPT_CREATED',
        receipt: cloneValue(receipt),
        historyEntry: createHistoryEntry(receipt)
      };
    }

    function createHistoryEntry(receipt) {
      const historyEntry = {
        request_id: receipt.request_id,
        project_id: receipt.project_id,
        operation: receipt.operation,
        destination: receipt.destination,
        status: receipt.status,
        affected_resource: receipt.affected_resource,
        commit_or_record_id: receipt.commit_or_record_id,
        source_commit: receipt.source_commit,
        timestamp: receipt.timestamp,
        failure_reason: receipt.failure_reason,
        receipt_json: JSON.stringify(receipt)
      };

      return HISTORY_FIELDS.reduce(function (entry, field) {
        entry[field] = historyEntry[field];
        return entry;
      }, {});
    }

    async function persistHistory(receiptResult, historyWriter) {
      if (!receiptResult || receiptResult.ok !== true || !receiptResult.historyEntry) {
        return {
          ok: false,
          outcome: 'HISTORY_NOT_ATTEMPTED',
          error: { code: 'INVALID_RECEIPT', message: 'A created receipt is required.' }
        };
      }

      if (!historyWriter || typeof historyWriter.appendHistory !== 'function') {
        return {
          ok: false,
          outcome: 'HISTORY_WRITE_FAILED',
          error: { code: 'INVALID_HISTORY_WRITER', message: 'An injected HISTORY writer is required.' }
        };
      }

      try {
        await historyWriter.appendHistory(cloneValue(receiptResult.historyEntry));
        return {
          ok: true,
          outcome: 'HISTORY_PERSISTED',
          receipt: cloneValue(receiptResult.receipt),
          historyEntry: cloneValue(receiptResult.historyEntry)
        };
      } catch (error) {
        return {
          ok: false,
          outcome: 'HISTORY_WRITE_FAILED',
          receipt: cloneValue(receiptResult.receipt),
          error: { code: 'HISTORY_WRITER_ERROR', message: 'HISTORY writer failed.' }
        };
      }
    }


    return Object.freeze({ createWriteReceipt, createHistoryEntry, persistHistory, HISTORY_FIELDS });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: flow/confirm-sync.mjs ----
  ASC_NS.flow = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    // T-008A — runtime-neutral preview → CONFIRM & SYNC → write/verify → receipt → HISTORY → redirect decision.
    //
    // This module only composes existing owners:
    //   - ASC Core (T-005)          validate / authorize / route
    //   - GitHub adapter (T-006)    read → write → read verification
    //   - Receipt + HISTORY (T-007) factual receipt and injected HISTORY persistence
    // It performs no I/O itself. All destination clients, HISTORY writers, clocks,
    // authorization policies, write-spec resolution, and the main ASC UI URL are injected.

    const { processCoreRequest } = ASC_NS.core;
    const { runGitHubAdapter } = ASC_NS.githubAdapter;
    const { createWriteReceipt, persistHistory } = ASC_NS.receipts;
    const CONFIRM_ACTION = 'CONFIRM_AND_SYNC';

    // v0.1 slice: only the GitHub adapter exists. Any other destination set fails closed
    // before any write so no partial persistence can occur.
    const SUPPORTED_DESTINATION_SETS = Object.freeze([['GitHub']]);

    function cloneValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function failed(stage, code, message, extra) {
      return {
        state: 'FAILED',
        stage,
        redirect: null,
        error: { code, message },
        ...(extra || {})
      };
    }

    function readEnvelope(envelope) {
      if (!envelope || typeof envelope !== 'object' || Array.isArray(envelope)) {
        return { error: failed('PREVIEW', 'INVALID_ENVELOPE', 'A decoded ASC envelope is required.') };
      }

      if (!isNonEmptyString(envelope.request_id)) {
        return { error: failed('PREVIEW', 'MISSING_REQUEST_ID', 'Envelope request_id is required.') };
      }

      return { requestId: envelope.request_id, contract: envelope.contract };
    }

    // Explicit confirmation must be an affirmative CONFIRM & SYNC action bound to this request.
    function isExplicitConfirmation(confirmation, requestId) {
      return Boolean(confirmation) &&
        typeof confirmation === 'object' &&
        confirmation.confirmed === true &&
        confirmation.action === CONFIRM_ACTION &&
        confirmation.requestId === requestId;
    }

    // Preview is pure: it never touches a destination client or HISTORY writer.
    function previewRequest(envelope) {
      const read = readEnvelope(envelope);
      if (read.error) {
        return read.error;
      }

      return {
        state: 'AWAITING_CONFIRMATION',
        stage: 'PREVIEW',
        redirect: null,
        requestId: read.requestId,
        contract: cloneValue(read.contract),
        confirmAction: CONFIRM_ACTION,
        writePerformed: false
      };
    }

    function isSupportedDestinationSet(routes) {
      const destinations = routes.map(function (route) { return route.destination; });
      return SUPPORTED_DESTINATION_SETS.some(function (set) {
        return set.length === destinations.length && set.every(function (d, i) { return destinations[i] === d; });
      });
    }

    // T-007 persistHistory treats only a thrown error as writer failure, while the Apps Script
    // History.gs writer reports failure as a returned { ok: false } value. Bridge both without
    // changing either owner: an explicit ok:false result is surfaced as a writer failure.
    function strictHistoryWriter(historyWriter) {
      if (!historyWriter || typeof historyWriter.appendHistory !== 'function') {
        return historyWriter;
      }

      return {
        appendHistory: async function (entry) {
          const result = await historyWriter.appendHistory(entry);
          if (result && typeof result === 'object' && result.ok === false) {
            throw new Error('HISTORY writer reported failure.');
          }
          return result;
        }
      };
    }

    function isValidRedirectUrl(url) {
      return isNonEmptyString(url) && /^https:\/\/[^\s]+$/.test(url);
    }

    async function confirmAndSyncRequest({
      envelope,
      confirmation,
      authorizationContext,
      authorizationPolicy,
      resolveGitHubWriteSpec,
      githubClient,
      historyWriter,
      now,
      sourceCommit = null,
      mainUiUrl
    } = {}) {
      const read = readEnvelope(envelope);
      if (read.error) {
        return read.error;
      }

      // Gate 1: no persistence of any kind without explicit, request-bound confirmation.
      if (!isExplicitConfirmation(confirmation, read.requestId)) {
        return {
          ...previewRequest(envelope),
          error: { code: 'CONFIRMATION_REQUIRED', message: 'Explicit CONFIRM & SYNC is required before persistence.' }
        };
      }

      // Gate 2: ASC Core validate / authorize / route. Rejection stops before any write.
      const core = processCoreRequest({
        contract: read.contract,
        authorizationContext,
        authorizationPolicy
      });

      if (core.status !== 'ACCEPTED') {
        return failed('CORE', 'CORE_REJECTED', 'ASC Core rejected the request at ' + core.stage + '.', {
          requestId: read.requestId,
          writePerformed: false,
          core: cloneValue(core)
        });
      }

      if (!isSupportedDestinationSet(core.routes)) {
        return failed('ROUTING', 'UNSUPPORTED_DESTINATION_SET', 'This v0.1 flow supports only Destination ["GitHub"].', {
          requestId: read.requestId,
          writePerformed: false
        });
      }

      if (typeof now !== 'function') {
        return failed('CONFIG', 'MISSING_CLOCK', 'A server clock is required for factual receipt timestamps.', {
          requestId: read.requestId,
          writePerformed: false
        });
      }

      if (typeof resolveGitHubWriteSpec !== 'function') {
        return failed('CONFIG', 'MISSING_WRITE_SPEC_RESOLVER', 'A server-side GitHub write-spec resolver is required.', {
          requestId: read.requestId,
          writePerformed: false
        });
      }

      const invocation = core.adapterInvocations[0];
      let writeSpec;
      try {
        writeSpec = resolveGitHubWriteSpec(cloneValue(invocation));
      } catch (error) {
        writeSpec = null;
      }

      // Gate 3: GitHub adapter owns read → write → read verification.
      const adapterResult = await runGitHubAdapter(invocation, writeSpec, githubClient);

      // Gate 4: T-007 factual receipt.
      const receiptResult = createWriteReceipt({
        requestId: read.requestId,
        projectId: read.contract.Project,
        operation: read.contract.Operation,
        sourceCommit,
        timestamp: now(),
        adapterResult
      });

      if (!receiptResult.ok) {
        return failed('RECEIPT', 'RECEIPT_NOT_CREATED', 'A factual receipt could not be created.', {
          requestId: read.requestId,
          writePerformed: adapterResult.writePerformed === true,
          adapterOutcome: adapterResult.outcome,
          receiptErrors: cloneValue(receiptResult.errors)
        });
      }

      // Gate 5: T-007 HISTORY persistence for both SUCCESS and FAILED receipts.
      const history = await persistHistory(receiptResult, strictHistoryWriter(historyWriter));
      const receipt = cloneValue(receiptResult.receipt);
      const base = {
        requestId: read.requestId,
        receipt,
        historyOutcome: history.outcome,
        writePerformed: receipt.write_performed
      };

      if (receipt.status !== 'SUCCESS' || receipt.verified !== true) {
        return failed('WRITE', 'WRITE_NOT_VERIFIED', receipt.failure_reason || 'Write was not verified.', base);
      }

      if (history.ok !== true) {
        return failed('HISTORY', 'HISTORY_NOT_PERSISTED', 'Verified write receipt exists but HISTORY was not persisted.', base);
      }

      if (!isValidRedirectUrl(mainUiUrl)) {
        // The write and HISTORY are factual successes; only the return path is unavailable.
        // Do not relabel persisted state as FAILED and do not invent a redirect target.
        return {
          state: 'SYNCED_REDIRECT_UNAVAILABLE',
          stage: 'REDIRECT',
          redirect: null,
          error: { code: 'MAIN_UI_URL_MISSING', message: 'Sync verified but the main ASC UI URL is not configured.' },
          ...base
        };
      }

      return {
        state: 'SYNCED',
        stage: 'REDIRECT',
        redirect: mainUiUrl,
        error: null,
        ...base
      };
    }

    return Object.freeze({ CONFIRM_ACTION, isExplicitConfirmation, previewRequest, confirmAndSyncRequest });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);
  ASC_RUNTIME_CACHE_ = Object.freeze(ASC_NS);
  return ASC_RUNTIME_CACHE_;
}
