// GENERATED by apps-script/build-runtime.mjs — DO NOT EDIT.
// Sources: transport/asc-link.mjs, transport/envelope-security.mjs, core/asc-core.mjs, adapters/github/github-adapter.mjs, adapters/github/github-rest-client.mjs, ci/zass-ci-status.mjs, continuity/private-continuity-state.mjs, continuity/index-freshness.mjs, continuity/github-source-head.mjs, receipts/write-receipt.mjs, flow/confirm-sync.mjs, receipts/History.gs
// Regenerate: node apps-script/build-runtime.mjs

// ==== verbatim: receipts/History.gs ====
const HISTORY_WRITER_CONFIG = Object.freeze({
  spreadsheetId: '11pWE0E-jEZhigVAYGcsfVXW0TODRcNMgOZHFfUQIHKw',
  sheetName: 'HISTORY'
});

const HISTORY_WRITER_HEADERS = Object.freeze([
  'request_id',
  'project_id',
  'operation',
  'destination',
  'status',
  'affected_resource',
  'commit_or_record_id',
  'source_commit',
  'timestamp',
  'failure_reason',
  'receipt_json'
]);

function appendHistory(historyEntry) {
  const validation = validateHistoryEntry_(historyEntry);
  if (!validation.valid) {
    return {
      ok: false,
      outcome: 'HISTORY_WRITE_FAILED',
      error: {
        code: 'INVALID_HISTORY_ENTRY',
        message: validation.errors.join('; ')
      }
    };
  }

  try {
    const sheet = SpreadsheetApp
      .openById(HISTORY_WRITER_CONFIG.spreadsheetId)
      .getSheetByName(HISTORY_WRITER_CONFIG.sheetName);

    if (!sheet) {
      return {
        ok: false,
        outcome: 'HISTORY_WRITE_FAILED',
        error: { code: 'HISTORY_SHEET_MISSING', message: 'HISTORY sheet is missing.' }
      };
    }

    const headers = sheet
      .getRange(1, 1, 1, HISTORY_WRITER_HEADERS.length)
      .getValues()[0];

    if (!HISTORY_WRITER_HEADERS.every(function (header, index) {
      return headers[index] === header;
    })) {
      return {
        ok: false,
        outcome: 'HISTORY_WRITE_FAILED',
        error: { code: 'HISTORY_HEADER_MISMATCH', message: 'HISTORY headers do not match.' }
      };
    }

    const row = HISTORY_WRITER_HEADERS.map(function (header) {
      return historyEntry[header];
    });
    sheet.appendRow(row);

    return {
      ok: true,
      outcome: 'HISTORY_PERSISTED',
      rowNumber: sheet.getLastRow()
    };
  } catch (error) {
    return {
      ok: false,
      outcome: 'HISTORY_WRITE_FAILED',
      error: { code: 'HISTORY_WRITER_EXCEPTION', message: 'HISTORY writer failed.' }
    };
  }
}

function validateHistoryEntry_(historyEntry) {
  const errors = [];
  const requiredStrings = [
    'request_id',
    'project_id',
    'operation',
    'timestamp',
    'receipt_json'
  ];

  if (!historyEntry || typeof historyEntry !== 'object') {
    return { valid: false, errors: ['History entry must be an object.'] };
  }

  requiredStrings.forEach(function (field) {
    if (typeof historyEntry[field] !== 'string' || historyEntry[field].length === 0) {
      errors.push(field + ' must be a non-empty string');
    }
  });

  if (historyEntry.status !== 'SUCCESS' && historyEntry.status !== 'FAILED') {
    errors.push('status must be SUCCESS or FAILED');
  }

  return { valid: errors.length === 0, errors: errors };
}

// ==== bundled ES modules (lazy, namespaced) ====
var ASC_RUNTIME_CACHE_ = null;

function ascRuntime_() {
  if (ASC_RUNTIME_CACHE_) {
    return ASC_RUNTIME_CACHE_;
  }
  const shims = ascRuntimeShims_();
  const ASC_NS = {};
  // ---- module: transport/asc-link.mjs ----
  ASC_NS.transport = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const ASC_FRAGMENT_KEY = "asc";
    const ENVELOPE_VERSION = "0.1";

    function utf8ToBase64Url(text) {
      const bytes = new TextEncoder().encode(text);
      let binary = "";
      for (const byte of bytes) binary += String.fromCharCode(byte);
      return btoa(binary)
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=+$/g, "");
    }

    function base64UrlToUtf8(value) {
      if (!/^[A-Za-z0-9_-]+$/.test(value)) {
        throw new Error("ASC fragment payload is not valid Base64URL.");
      }

      const padded = value
        .replace(/-/g, "+")
        .replace(/_/g, "/")
        .padEnd(Math.ceil(value.length / 4) * 4, "=");

      const binary = atob(padded);
      const bytes = Uint8Array.from(binary, ch => ch.charCodeAt(0));
      return new TextDecoder().decode(bytes);
    }

    function createEnvelope(contract, options = {}) {
      if (!contract || typeof contract !== "object" || Array.isArray(contract)) {
        throw new Error("contract must be a JSON object.");
      }

      const requestId = String(options.requestId ?? "").trim();
      const issuedAt = String(options.issuedAt ?? "").trim();
      const expiresAt = String(options.expiresAt ?? "").trim();

      if (!requestId) throw new Error("requestId is required.");
      if (!issuedAt || Number.isNaN(Date.parse(issuedAt))) {
        throw new Error("issuedAt must be a valid date-time string.");
      }
      if (!expiresAt || Number.isNaN(Date.parse(expiresAt))) {
        throw new Error("expiresAt must be a valid date-time string.");
      }

      // T-010 (D-029): issued_at / expires_at / integrity are transport/security metadata.
      // The digest is filled by sealEnvelope() in envelope-security.mjs; null = unsealed,
      // which server-side security validation rejects.
      return {
        envelope_version: ENVELOPE_VERSION,
        request_id: requestId,
        issued_at: issuedAt,
        expires_at: expiresAt,
        integrity: {
          algorithm: "SHA-256",
          digest: options.integrityDigest ?? null
        },
        contract
      };
    }

    function encodeEnvelope(envelope) {
      if (!envelope || typeof envelope !== "object" || Array.isArray(envelope)) {
        throw new Error("envelope must be a JSON object.");
      }
      return utf8ToBase64Url(JSON.stringify(envelope));
    }

    function decodeEnvelope(encodedPayload) {
      const json = base64UrlToUtf8(encodedPayload);
      const envelope = JSON.parse(json);

      if (envelope?.envelope_version !== ENVELOPE_VERSION) {
        throw new Error("Unsupported ASC envelope version.");
      }

      return envelope;
    }

    function buildAscLink(baseUrl, envelope) {
      const url = new URL(baseUrl);
      url.hash = "";
      url.searchParams.delete(ASC_FRAGMENT_KEY);

      const encoded = encodeEnvelope(envelope);
      url.hash = `${ASC_FRAGMENT_KEY}=${encoded}`;
      return url.toString();
    }

    function decodeAscLink(link) {
      const url = new URL(link);

      if (url.searchParams.has(ASC_FRAGMENT_KEY)) {
        throw new Error("ASC payload must not be carried in ordinary query parameters.");
      }

      const fragment = url.hash.startsWith("#") ? url.hash.slice(1) : url.hash;
      const prefix = `${ASC_FRAGMENT_KEY}=`;

      if (!fragment.startsWith(prefix)) {
        throw new Error("ASC fragment payload is missing.");
      }

      const encoded = fragment.slice(prefix.length);
      if (!encoded) throw new Error("ASC fragment payload is empty.");

      return decodeEnvelope(encoded);
    }

    const ASC_LINK_CONSTANTS = Object.freeze({
      fragmentKey: ASC_FRAGMENT_KEY,
      envelopeVersion: ENVELOPE_VERSION
    });

    return Object.freeze({ createEnvelope, encodeEnvelope, decodeEnvelope, buildAscLink, decodeAscLink, ASC_LINK_CONSTANTS });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: transport/envelope-security.mjs ----
  ASC_NS.security = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    // T-010A — runtime-neutral ASC envelope security validation (D-029).
    //
    // Pure functions only: no network, no persistence, no clock or crypto of its own.
    // The SHA-256 implementation (`sha256Hex(text) -> lowercase hex`, UTF-8 input) and the
    // validation time are injected so the same code runs in Node and Apps Script.
    //
    // Boundary: SHA-256 carried with the payload gives integrity consistency / error detection
    // only. It is NOT sender authentication, a signature, or a MAC: anyone able to rewrite the
    // payload can also recompute the digest. Owner identity and the replay claim are enforced
    // separately by the server binding.

    const SECURITY_ENVELOPE_VERSION = '0.1';
    const INTEGRITY_ALGORITHM = 'SHA-256';
    const MAX_LIFETIME_MS = 30 * 60 * 1000;

    const ENVELOPE_KEYS = Object.freeze(['contract', 'envelope_version', 'expires_at', 'integrity', 'issued_at', 'request_id']);
    const INTEGRITY_KEYS = Object.freeze(['algorithm', 'digest']);
    const DIGEST_PATTERN = /^[0-9a-f]{64}$/;
    const ISO_PATTERN = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(\.\d{1,3})?(Z|([+-])(\d{2}):(\d{2}))$/;

    function isPlainObject(value) {
      return value !== null && typeof value === 'object' && !Array.isArray(value);
    }

    function reject(code, message) {
      return { ok: false, code, message };
    }

    function sameKeys(value, expected) {
      const keys = Object.keys(value).sort();
      return keys.length === expected.length && keys.every(function (k, i) { return k === expected[i]; });
    }

    // Deterministic canonical JSON: object keys sorted recursively, array order preserved,
    // scalars serialized exactly as JSON.stringify does. Non-JSON values throw.
    function canonicalJson(value) {
      if (value === null || typeof value === 'string' || typeof value === 'boolean') {
        return JSON.stringify(value);
      }
      if (typeof value === 'number') {
        if (!Number.isFinite(value)) {
          throw new Error('Non-finite number is not canonical JSON.');
        }
        return JSON.stringify(value);
      }
      if (Array.isArray(value)) {
        return '[' + value.map(canonicalJson).join(',') + ']';
      }
      if (isPlainObject(value)) {
        return '{' + Object.keys(value).sort().map(function (key) {
          return JSON.stringify(key) + ':' + canonicalJson(value[key]);
        }).join(',') + '}';
      }
      throw new Error('Unsupported value in canonical JSON.');
    }

    // The digest input: everything except the integrity object itself.
    function integrityPayload(envelope) {
      return {
        envelope_version: envelope.envelope_version,
        request_id: envelope.request_id,
        issued_at: envelope.issued_at,
        expires_at: envelope.expires_at,
        contract: envelope.contract
      };
    }

    function digestOf(envelope, sha256Hex) {
      const digest = sha256Hex(canonicalJson(integrityPayload(envelope)));
      if (typeof digest !== 'string' || !DIGEST_PATTERN.test(digest)) {
        throw new Error('Digest implementation returned an invalid SHA-256 hex value.');
      }
      return digest;
    }

    // Returns a copy of the envelope with integrity.digest set. Used by link generators/tests.
    function sealEnvelope(envelope, sha256Hex) {
      if (typeof sha256Hex !== 'function') {
        throw new Error('sha256Hex implementation is required.');
      }
      const sealed = JSON.parse(JSON.stringify(envelope));
      sealed.integrity = { algorithm: INTEGRITY_ALGORITHM, digest: digestOf(sealed, sha256Hex) };
      return sealed;
    }

    // Strict ISO 8601 date-time with explicit offset; returns epoch ms or null.
    function parseIsoDateTime(value) {
      if (typeof value !== 'string') return null;
      const m = ISO_PATTERN.exec(value);
      if (!m) return null;
      const year = Number(m[1]);
      const month = Number(m[2]);
      const day = Number(m[3]);
      const hour = Number(m[4]);
      const minute = Number(m[5]);
      const second = Number(m[6]);
      if (month < 1 || month > 12 || hour > 23 || minute > 59 || second > 59) return null;
      if (new Date(Date.UTC(year, month - 1, day)).getUTCDate() !== day || day < 1) return null;
      if (m[9] !== undefined && (Number(m[10]) > 23 || Number(m[11]) > 59)) return null;
      const ms = Date.parse(value);
      return Number.isFinite(ms) ? ms : null;
    }

    // Structural + expiry/lifetime + integrity validation. Order (D-029):
    // structure → timestamps → lifetime → not expired → algorithm/digest format → digest match.
    function validateEnvelopeSecurity(envelope, { now, sha256Hex } = {}) {
      if (typeof now !== 'function' || typeof sha256Hex !== 'function') {
        return reject('SECURITY_CONFIG_MISSING', 'Server clock and SHA-256 implementation are required.');
      }
      if (!isPlainObject(envelope)) {
        return reject('INVALID_ENVELOPE', 'A decoded ASC envelope object is required.');
      }
      if (envelope.envelope_version !== SECURITY_ENVELOPE_VERSION) {
        return reject('UNSUPPORTED_ENVELOPE_VERSION', 'Unsupported ASC envelope version.');
      }
      if (!sameKeys(envelope, ENVELOPE_KEYS)) {
        return reject('INVALID_ENVELOPE', 'Envelope must contain exactly envelope_version, request_id, issued_at, expires_at, integrity, contract.');
      }
      if (typeof envelope.request_id !== 'string' || envelope.request_id.length === 0) {
        return reject('MISSING_REQUEST_ID', 'Envelope request_id is required.');
      }
      if (!isPlainObject(envelope.contract)) {
        return reject('INVALID_ENVELOPE', 'Envelope contract must be a JSON object.');
      }

      const issuedMs = parseIsoDateTime(envelope.issued_at);
      const expiresMs = parseIsoDateTime(envelope.expires_at);
      if (issuedMs === null || expiresMs === null) {
        return reject('INVALID_TIMESTAMP', 'issued_at and expires_at must be valid ISO date-time strings with an explicit offset.');
      }
      if (expiresMs <= issuedMs) {
        return reject('INVALID_LIFETIME', 'expires_at must be later than issued_at.');
      }
      if (expiresMs - issuedMs > MAX_LIFETIME_MS) {
        return reject('LIFETIME_EXCEEDED', 'Envelope lifetime exceeds 30 minutes.');
      }

      let nowMs;
      try {
        nowMs = Date.parse(now());
      } catch (error) {
        nowMs = NaN;
      }
      if (!Number.isFinite(nowMs)) {
        return reject('SECURITY_CLOCK_INVALID', 'Server clock did not return a valid date-time.');
      }
      if (nowMs >= expiresMs) {
        return reject('REQUEST_EXPIRED', 'ASC request has expired.');
      }
      // Remaining lifetime may never exceed the maximum either (e.g. issued_at in the future).
      if (expiresMs - nowMs > MAX_LIFETIME_MS) {
        return reject('LIFETIME_EXCEEDED', 'Remaining envelope lifetime exceeds 30 minutes.');
      }

      const integrity = envelope.integrity;
      if (!isPlainObject(integrity) || !sameKeys(integrity, INTEGRITY_KEYS)) {
        return reject('INTEGRITY_MISSING', 'Envelope integrity must contain exactly algorithm and digest.');
      }
      if (integrity.algorithm !== INTEGRITY_ALGORITHM) {
        return reject('INTEGRITY_ALGORITHM_UNSUPPORTED', 'integrity.algorithm must be SHA-256.');
      }
      if (typeof integrity.digest !== 'string' || !DIGEST_PATTERN.test(integrity.digest)) {
        return reject('INTEGRITY_DIGEST_INVALID', 'integrity.digest must be a lowercase 64-character SHA-256 hex digest.');
      }

      let expected;
      try {
        expected = digestOf(envelope, sha256Hex);
      } catch (error) {
        return reject('INTEGRITY_UNAVAILABLE', 'Integrity digest could not be computed.');
      }
      if (expected !== integrity.digest) {
        return reject('INTEGRITY_MISMATCH', 'Envelope content does not match its SHA-256 digest.');
      }

      return {
        ok: true,
        requestId: envelope.request_id,
        issuedAt: envelope.issued_at,
        expiresAt: envelope.expires_at,
        algorithm: INTEGRITY_ALGORITHM
      };
    }

    return Object.freeze({ SECURITY_ENVELOPE_VERSION, INTEGRITY_ALGORITHM, MAX_LIFETIME_MS, canonicalJson, integrityPayload, sealEnvelope, parseIsoDateTime, validateEnvelopeSecurity });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: core/asc-core.mjs ----
  ASC_NS.core = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const CONTRACT_FIELDS = Object.freeze([
      'Project',
      'Source method',
      'Operation',
      'Record type',
      'Record ID',
      'Content/change',
      'Lineage',
      'Destination'
    ]);

    const DESTINATION_ADAPTERS = Object.freeze({
      GitHub: 'github',
      ASC_DB: 'asc_db'
    });

    function cloneSemanticValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneSemanticValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneSemanticValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function hasUniqueStrings(values) {
      return values.every(isNonEmptyString) && new Set(values).size === values.length;
    }

    function validationError(code, field, message) {
      return { code, field, message };
    }

    function validateContract(contract) {
      const errors = [];

      if (contract === null || typeof contract !== 'object' || Array.isArray(contract)) {
        return {
          valid: false,
          errors: [validationError('INVALID_TYPE', null, 'Contract must be an object.')]
        };
      }

      const actualFields = Object.keys(contract);
      const expectedFields = new Set(CONTRACT_FIELDS);

      CONTRACT_FIELDS.forEach(function (field) {
        if (!Object.prototype.hasOwnProperty.call(contract, field)) {
          errors.push(validationError('MISSING_FIELD', field, 'Required field is missing.'));
        }
      });

      actualFields.forEach(function (field) {
        if (!expectedFields.has(field)) {
          errors.push(validationError('EXTRA_FIELD', field, 'Top-level field is not allowed.'));
        }
      });

      ['Project', 'Source method', 'Operation', 'Record type', 'Record ID'].forEach(function (field) {
        if (Object.prototype.hasOwnProperty.call(contract, field) && !isNonEmptyString(contract[field])) {
          errors.push(validationError('INVALID_STRING', field, 'Value must be a non-empty string.'));
        }
      });

      if (Object.prototype.hasOwnProperty.call(contract, 'Content/change')) {
        const content = contract['Content/change'];
        const validContent = isNonEmptyString(content) ||
          Array.isArray(content) ||
          (content !== null && typeof content === 'object');

        if (!validContent) {
          errors.push(validationError(
            'INVALID_CONTENT',
            'Content/change',
            'Value must be an object, array, or non-empty string.'
          ));
        }
      }

      if (Object.prototype.hasOwnProperty.call(contract, 'Lineage')) {
        if (!Array.isArray(contract.Lineage)) {
          errors.push(validationError('INVALID_ARRAY', 'Lineage', 'Value must be an array.'));
        } else if (!hasUniqueStrings(contract.Lineage)) {
          errors.push(validationError(
            'INVALID_LINEAGE',
            'Lineage',
            'Items must be unique non-empty strings.'
          ));
        }
      }

      if (Object.prototype.hasOwnProperty.call(contract, 'Destination')) {
        if (!Array.isArray(contract.Destination) || contract.Destination.length === 0) {
          errors.push(validationError(
            'INVALID_DESTINATION',
            'Destination',
            'Value must contain at least one destination.'
          ));
        } else if (!hasUniqueStrings(contract.Destination)) {
          errors.push(validationError(
            'INVALID_DESTINATION',
            'Destination',
            'Items must be unique non-empty strings.'
          ));
        }
      }

      return {
        valid: errors.length === 0,
        errors
      };
    }

    function authorizeRequest(contract, authorizationContext, authorizationPolicy) {
      if (typeof authorizationPolicy !== 'function') {
        return {
          authorized: false,
          errors: [{ code: 'AUTHORIZATION_POLICY_REQUIRED', message: 'Authorization policy is required.' }]
        };
      }

      let decision;
      try {
        decision = authorizationPolicy(
          cloneSemanticValue(contract),
          authorizationContext
        );
      } catch (error) {
        return {
          authorized: false,
          errors: [{ code: 'AUTHORIZATION_POLICY_ERROR', message: 'Authorization policy failed.' }]
        };
      }

      if (!decision || decision.authorized !== true) {
        return {
          authorized: false,
          errors: [{ code: 'AUTHORIZATION_DENIED', message: 'Authorization policy did not authorize the request.' }]
        };
      }

      return {
        authorized: true,
        errors: []
      };
    }

    function routeDestinations(contract) {
      const routes = [];

      for (const destination of contract.Destination) {
        const adapterId = DESTINATION_ADAPTERS[destination];
        if (!adapterId) {
          return {
            routed: false,
            routes: [],
            error: {
              code: 'UNSUPPORTED_DESTINATION',
              destination,
              message: 'Destination is not supported by this Core proof.'
            }
          };
        }

        routes.push({ destination, adapterId });
      }

      return {
        routed: true,
        routes,
        error: null
      };
    }

    function createAdapterInvocation(contract, route) {
      return {
        destination: route.destination,
        adapterId: route.adapterId,
        contract: cloneSemanticValue(contract)
      };
    }

    function createReceiptLayerHandoff(adapterResult) {
      return {
        kind: 'ADAPTER_RESULT_TO_RECEIPT_LAYER',
        adapterResult: cloneSemanticValue(adapterResult)
      };
    }

    function processCoreRequest({
      contract,
      authorizationContext,
      authorizationPolicy
    }) {
      const validation = validateContract(contract);

      if (!validation.valid) {
        return {
          status: 'REJECTED',
          stage: 'VALIDATION',
          validation
        };
      }

      const authorization = authorizeRequest(
        contract,
        authorizationContext,
        authorizationPolicy
      );

      if (!authorization.authorized) {
        return {
          status: 'REJECTED',
          stage: 'AUTHORIZATION',
          validation,
          authorization
        };
      }

      const preservedContract = cloneSemanticValue(contract);
      const routing = routeDestinations(preservedContract);

      if (!routing.routed) {
        return {
          status: 'REJECTED',
          stage: 'ROUTING',
          validation,
          authorization,
          routing,
          contract: preservedContract
        };
      }

      const adapterInvocations = routing.routes.map(function (route) {
        return createAdapterInvocation(preservedContract, route);
      });

      return {
        status: 'ACCEPTED',
        stage: 'CORE_BOUNDARY',
        validation,
        authorization,
        contract: preservedContract,
        routes: routing.routes,
        adapterInvocations,
        receiptLayerHandoff: {
          kind: 'ADAPTER_RESULTS_PENDING_RECEIPT_LAYER',
          adapterResults: []
        }
      };
    }

    return Object.freeze({ validateContract, authorizeRequest, routeDestinations, createAdapterInvocation, createReceiptLayerHandoff, processCoreRequest });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: adapters/github/github-adapter.mjs ----
  ASC_NS.githubAdapter = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const INVOCATION_FIELDS = Object.freeze(['destination', 'adapterId', 'contract']);
    const WRITE_SPEC_FIELDS = Object.freeze([
      'repository',
      'path',
      'branch',
      'content',
      'commitMessage'
    ]);

    function cloneValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function errorResult(code, message, field) {
      return { code, message, ...(field ? { field } : {}) };
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function hasOnlyFields(value, fields) {
      return Object.keys(value).every(function (key) {
        return fields.includes(key);
      });
    }

    function validateGitHubInvocation(invocation) {
      const errors = [];

      if (invocation === null || typeof invocation !== 'object' || Array.isArray(invocation)) {
        return {
          valid: false,
          errors: [errorResult('INVALID_INVOCATION', 'Invocation must be an object.')]
        };
      }

      if (invocation.destination !== 'GitHub') {
        errors.push(errorResult('INVALID_DESTINATION', 'Invocation destination must be GitHub.', 'destination'));
      }

      if (invocation.adapterId !== 'github') {
        errors.push(errorResult('INVALID_ADAPTER', 'Invocation adapterId must be github.', 'adapterId'));
      }

      if (invocation.contract === null || typeof invocation.contract !== 'object' || Array.isArray(invocation.contract)) {
        errors.push(errorResult('INVALID_CONTRACT', 'Invocation contract must be an object.', 'contract'));
      }

      return { valid: errors.length === 0, errors };
    }

    function validateGitHubWriteSpec(writeSpec) {
      const errors = [];

      if (writeSpec === null || typeof writeSpec !== 'object' || Array.isArray(writeSpec)) {
        return {
          valid: false,
          errors: [errorResult('INVALID_WRITE_SPEC', 'Write spec must be an object.')]
        };
      }

      if (!hasOnlyFields(writeSpec, WRITE_SPEC_FIELDS)) {
        errors.push(errorResult('EXTRA_WRITE_SPEC_FIELD', 'Write spec contains an unsupported field.'));
      }

      ['repository', 'path', 'branch', 'commitMessage'].forEach(function (field) {
        if (!isNonEmptyString(writeSpec[field])) {
          errors.push(errorResult('INVALID_WRITE_SPEC_FIELD', 'Write spec field must be a non-empty string.', field));
        }
      });

      if (typeof writeSpec.content !== 'string') {
        errors.push(errorResult('INVALID_WRITE_SPEC_FIELD', 'Write spec content must be a string.', 'content'));
      }

      return { valid: errors.length === 0, errors };
    }

    function invalidInputResult(validation, writeSpecValidation) {
      return {
        outcome: 'INVALID_INPUT',
        writePerformed: false,
        verified: false,
        validation,
        writeSpecValidation
      };
    }

    function clientError(code, message) {
      return {
        ok: false,
        error: errorResult(code, message)
      };
    }

    async function callClient(method, input) {
      try {
        return await method(cloneValue(input));
      } catch (error) {
        return clientError('CLIENT_EXCEPTION', 'Injected GitHub client call failed.');
      }
    }

    function isValidReadResult(readResult) {
      if (!readResult || typeof readResult !== 'object' || typeof readResult.ok !== 'boolean') {
        return false;
      }

      if (!readResult.ok || typeof readResult.found !== 'boolean') {
        return false;
      }

      if (!readResult.found) {
        return readResult.sha === null && readResult.content === null;
      }

      return isNonEmptyString(readResult.sha) && typeof readResult.content === 'string';
    }

    function readFailure(readResult, code, message) {
      return {
        outcome: 'READ_ERROR',
        writePerformed: false,
        verified: false,
        error: cloneValue(readResult && readResult.error) || errorResult(
          code || 'READ_ERROR',
          message || 'GitHub read failed.'
        )
      };
    }

    function writeUnverifiedResult(writeSpec, commitSha, contentSha, persistedSha, error) {
      return {
        outcome: 'WRITE_UNVERIFIED',
        adapterId: 'github',
        destination: 'GitHub',
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch,
        writePerformed: true,
        commitSha,
        contentSha,
        persistedSha,
        verified: false,
        error: cloneValue(error)
      };
    }

    function isValidWriteResult(writeResult) {
      return writeResult !== null &&
        typeof writeResult === 'object' &&
        typeof writeResult.ok === 'boolean' &&
        (!writeResult.ok || isNonEmptyString(writeResult.commitSha));
    }

    async function runGitHubAdapter(invocation, writeSpec, githubClient) {
      const validation = validateGitHubInvocation(invocation);
      const writeSpecValidation = validateGitHubWriteSpec(writeSpec);

      if (!validation.valid || !writeSpecValidation.valid) {
        return invalidInputResult(validation, writeSpecValidation);
      }

      if (!githubClient || typeof githubClient.readFile !== 'function' || typeof githubClient.writeFile !== 'function') {
        return invalidInputResult(
          validation,
          {
            valid: false,
            errors: [errorResult('INVALID_CLIENT', 'Injected GitHub client must expose readFile and writeFile.')]
          }
        );
      }

      const readInput = {
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch
      };
      const currentRead = await callClient(githubClient.readFile.bind(githubClient), readInput);

      if (!currentRead || currentRead.ok !== true) {
        return readFailure(currentRead || clientError('READ_ERROR', 'GitHub read failed.'));
      }

      if (!isValidReadResult(currentRead)) {
        return readFailure(
          currentRead,
          'MALFORMED_READ_RESULT',
          'GitHub read result was malformed.'
        );
      }

      if (currentRead.found === true && currentRead.content === writeSpec.content) {
        return {
          outcome: 'NO_CHANGE',
          adapterId: 'github',
          destination: 'GitHub',
          repository: writeSpec.repository,
          path: writeSpec.path,
          branch: writeSpec.branch,
          writePerformed: false,
          commitSha: null,
          existingSha: currentRead.sha || null,
          contentSha: currentRead.sha || null,
          verified: true
        };
      }

      const writeInput = {
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch,
        content: writeSpec.content,
        commitMessage: writeSpec.commitMessage
      };

      if (currentRead.found === true) {
        if (!isNonEmptyString(currentRead.sha)) {
          return readFailure(
            currentRead,
            'MISSING_CURRENT_SHA',
            'Existing GitHub file did not provide a current SHA.'
          );
        }
        writeInput.sha = currentRead.sha;
      }

      const writeResult = await callClient(githubClient.writeFile.bind(githubClient), writeInput);

      if (!writeResult || writeResult.ok !== true) {
        return {
          outcome: 'WRITE_ERROR',
          adapterId: 'github',
          destination: 'GitHub',
          repository: writeSpec.repository,
          path: writeSpec.path,
          branch: writeSpec.branch,
          writePerformed: false,
          commitSha: writeResult && writeResult.commitSha ? writeResult.commitSha : null,
          verified: false,
          error: cloneValue(writeResult && writeResult.error) || errorResult('WRITE_ERROR', 'GitHub write failed.')
        };
      }

      const commitSha = isNonEmptyString(writeResult.commitSha) ? writeResult.commitSha : null;
      const writeResponseValid = isValidWriteResult(writeResult);
      const persistedRead = await callClient(githubClient.readFile.bind(githubClient), readInput);

      if (!persistedRead || persistedRead.ok !== true) {
        return writeUnverifiedResult(
          writeSpec,
          commitSha,
          null,
          null,
          cloneValue(persistedRead && persistedRead.error) || errorResult('VERIFY_READ_ERROR', 'Persisted-state read failed.')
        );
      }

      if (!isValidReadResult(persistedRead)) {
        return writeUnverifiedResult(
          writeSpec,
          commitSha,
          null,
          null,
          errorResult('MALFORMED_VERIFY_RESULT', 'Persisted-state read result was malformed.')
        );
      }

      if (!writeResponseValid || persistedRead.found !== true || persistedRead.content !== writeSpec.content) {
        return writeUnverifiedResult(
          writeSpec,
          commitSha,
          null,
          persistedRead.sha,
          errorResult('CONTENT_MISMATCH', 'Persisted content or write response did not verify the proposed write.')
        );
      }

      return {
        outcome: 'VERIFIED_WRITE',
        adapterId: 'github',
        destination: 'GitHub',
        repository: writeSpec.repository,
        path: writeSpec.path,
        branch: writeSpec.branch,
        writePerformed: true,
        commitSha,
        contentSha: persistedRead.sha,
        persistedSha: persistedRead.sha,
        verified: true
      };
    }

    return Object.freeze({ validateGitHubInvocation, validateGitHubWriteSpec, runGitHubAdapter });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: adapters/github/github-rest-client.mjs ----
  ASC_NS.githubRest = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const API_ROOT = 'https://api.github.com';
    const API_HEADERS = Object.freeze({
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'AISYNC-T006B-GitHub-REST-Client'
    });

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function errorResult(code, message, status) {
      return {
        ok: false,
        error: {
          code,
          message,
          ...(typeof status === 'number' ? { status } : {})
        }
      };
    }

    function validateRepository(repository) {
      return typeof repository === 'string' && /^[^/\s]+\/[^/\s]+$/.test(repository);
    }

    function validateReadInput(input) {
      if (!input || !validateRepository(input.repository)) {
        return errorResult('INVALID_REPOSITORY', 'Repository must use owner/repository form.');
      }

      if (!isNonEmptyString(input.path)) {
        return errorResult('INVALID_PATH', 'Path must be a non-empty string.');
      }

      if (!isNonEmptyString(input.branch)) {
        return errorResult('INVALID_BRANCH', 'Branch must be a non-empty string.');
      }

      return null;
    }

    function validateWriteInput(input) {
      const readError = validateReadInput(input);
      if (readError) {
        return readError;
      }

      if (typeof input.content !== 'string') {
        return errorResult('INVALID_CONTENT', 'Content must be a string.');
      }

      if (!isNonEmptyString(input.commitMessage)) {
        return errorResult('INVALID_COMMIT_MESSAGE', 'Commit message must be a non-empty string.');
      }

      if (Object.prototype.hasOwnProperty.call(input, 'sha') && !isNonEmptyString(input.sha)) {
        return errorResult('INVALID_SHA', 'SHA must be a non-empty string when supplied.');
      }

      return null;
    }

    function buildFileUrl(input) {
      const encodedPath = input.path
        .split('/')
        .map(encodeURIComponent)
        .join('/');

      return API_ROOT + '/repos/' + input.repository + '/contents/' + encodedPath +
        '?ref=' + encodeURIComponent(input.branch);
    }

    function createHeaders(token) {
      return {
        ...API_HEADERS,
        Authorization: 'Bearer ' + token
      };
    }

    async function readJson(response) {
      try {
        return await response.json();
      } catch (error) {
        return null;
      }
    }

    function decodeBase64Utf8(value) {
      if (typeof value !== 'string') {
        throw new Error('Base64 content is not a string.');
      }

      const compact = value.replace(/\s/g, '');
      if (!compact || compact.length % 4 === 1 || !/^[A-Za-z0-9+/]*={0,2}$/.test(compact)) {
        throw new Error('Base64 content is malformed.');
      }

      const paddingIndex = compact.indexOf('=');
      if (paddingIndex >= 0 && paddingIndex < compact.length - 2) {
        throw new Error('Base64 padding is malformed.');
      }

      const bytes = Buffer.from(compact, 'base64');
      const canonical = bytes.toString('base64').replace(/=+$/, '');
      if (canonical !== compact.replace(/=+$/, '')) {
        throw new Error('Base64 content is malformed.');
      }

      return bytes.toString('utf8');
    }

    function validateConfig(token, fetchImpl) {
      if (!isNonEmptyString(token)) {
        return errorResult('MISSING_TOKEN', 'GitHub token configuration is missing.');
      }

      if (typeof fetchImpl !== 'function') {
        return errorResult('MISSING_FETCH', 'Fetch implementation is missing.');
      }

      return null;
    }

    function fetchFailure(errorCode, message) {
      return errorResult(errorCode, message);
    }

    function createGitHubRestClient({ token, fetchImpl = globalThis.fetch } = {}) {
      const configError = validateConfig(token, fetchImpl);

      async function readFile(input) {
        const inputError = configError || validateReadInput(input);
        if (inputError) {
          return inputError;
        }

        try {
          const response = await fetchImpl(buildFileUrl(input), {
            method: 'GET',
            headers: createHeaders(token)
          });

          if (response.status === 404) {
            return { ok: true, found: false, sha: null, content: null };
          }

          if (response.status < 200 || response.status >= 300) {
            return errorResult('GITHUB_READ_FAILED', 'GitHub read request failed.', response.status);
          }

          const data = await readJson(response);
          if (!data || data.type !== 'file' || !isNonEmptyString(data.sha) || typeof data.content !== 'string') {
            return errorResult('MALFORMED_READ_RESPONSE', 'GitHub read response was not a valid file.');
          }

          let content;
          try {
            content = decodeBase64Utf8(data.content);
          } catch (error) {
            return errorResult('MALFORMED_FILE_CONTENT', 'GitHub file content was not valid Base64.');
          }

          return {
            ok: true,
            found: true,
            sha: data.sha,
            content
          };
        } catch (error) {
          return fetchFailure('GITHUB_FETCH_ERROR', 'GitHub request could not be completed.');
        }
      }

      async function writeFile(input) {
        const inputError = configError || validateWriteInput(input);
        if (inputError) {
          return inputError;
        }

        const body = {
          message: input.commitMessage,
          content: Buffer.from(input.content, 'utf8').toString('base64'),
          branch: input.branch
        };

        if (Object.prototype.hasOwnProperty.call(input, 'sha')) {
          body.sha = input.sha;
        }

        try {
          const response = await fetchImpl(buildFileUrl(input), {
            method: 'PUT',
            headers: createHeaders(token),
            body: JSON.stringify(body)
          });

          if (response.status < 200 || response.status >= 300) {
            return errorResult('GITHUB_WRITE_FAILED', 'GitHub write request failed.', response.status);
          }

          const data = await readJson(response);
          if (!data || !data.commit || !isNonEmptyString(data.commit.sha) ||
            !data.content || !isNonEmptyString(data.content.sha)) {
            return errorResult('MALFORMED_WRITE_RESPONSE', 'GitHub write response lacked valid identifiers.');
          }

          return {
            ok: true,
            commitSha: data.commit.sha,
            contentSha: data.content.sha
          };
        } catch (error) {
          return fetchFailure('GITHUB_FETCH_ERROR', 'GitHub request could not be completed.');
        }
      }

      return { readFile, writeFile };
    }

    return Object.freeze({ createGitHubRestClient });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: ci/zass-ci-status.mjs ----
  ASC_NS.zassCi = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const API_ROOT = 'https://api.github.com';
    const API_HEADERS = Object.freeze({
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'AISYNC-T012A-ZASS-CI-Consumer'
    });

    const WORKFLOW_NAME = 'ZASS CI';
    const JOB_NAME = 'zass-check';

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function validateRepository(repository) {
      return typeof repository === 'string' &&
        /^[^/\s]+\/[^/\s]+$/.test(repository);
    }

    function validateCommitSha(commitSha) {
      return typeof commitSha === 'string' && /^[0-9a-f]{40}$/i.test(commitSha);
    }

    function encodeRepository(repository) {
      return repository.split('/').map(encodeURIComponent).join('/');
    }

    function fetchedAt(now) {
      try {
        return now();
      } catch (error) {
        return null;
      }
    }
    function baseModel(repository, commitSha, now) {
      return {
        repository: repository || null,
        commit_sha: commitSha || null,
        workflow_name: WORKFLOW_NAME,
        job_name: JOB_NAME,
        run_id: null,
        status: null,
        conclusion: null,
        run_url: null,
        fetched_at: fetchedAt(now)
      };
    }

    function readError(repository, commitSha, now, code, message, httpStatus) {
      return {
        ok: false,
        ...baseModel(repository, commitSha, now),
        status: 'READ_ERROR',
        error: {
          code,
          message,
          ...(typeof httpStatus === 'number' ? { http_status: httpStatus } : {})
        }
      };
    }

    function notFound(repository, commitSha, now) {
      return {
        ok: true,
        ...baseModel(repository, commitSha, now),
        status: 'NOT_FOUND'
      };
    }
    function createHeaders(token) {
      const headers = { ...API_HEADERS };
      if (isNonEmptyString(token)) {
        headers.Authorization = 'Bearer ' + token;
      }
      return headers;
    }

    async function readJson(response) {
      try {
        return await response.json();
      } catch (error) {
        return null;
      }
    }

    async function fetchJson(fetchImpl, url, headers) {
      let response;
      try {
        response = await fetchImpl(url, {
          method: 'GET',
          headers
        });
      } catch (error) {
        return { ok: false, code: 'GITHUB_FETCH_ERROR', message: 'GitHub request could not be completed.' };
      }

      if (!response || typeof response.status !== 'number') {
        return { ok: false, code: 'MALFORMED_HTTP_RESPONSE', message: 'GitHub response was malformed.' };
      }

      if (response.status < 200 || response.status >= 300) {
        return {
          ok: false,
          code: 'GITHUB_READ_FAILED',
          message: 'GitHub read request failed.',
          httpStatus: response.status
        };
      }
      const data = await readJson(response);
      if (data === null) {
        return { ok: false, code: 'MALFORMED_JSON_RESPONSE', message: 'GitHub response JSON was malformed.' };
      }

      return { ok: true, data };
    }

    function selectWorkflowRun(workflowRuns, commitSha) {
      const matches = workflowRuns.filter(function (run) {
        return run &&
          run.name === WORKFLOW_NAME &&
          run.head_sha === commitSha &&
          Number.isSafeInteger(run.id);
      });

      if (matches.length === 0) {
        return null;
      }

      return matches.slice().sort(function (a, b) {
        const attemptA = Number.isSafeInteger(a.run_attempt) ? a.run_attempt : 0;
        const attemptB = Number.isSafeInteger(b.run_attempt) ? b.run_attempt : 0;
        if (attemptA !== attemptB) return attemptB - attemptA;
        return b.id - a.id;
      })[0];
    }

    function normalizeJobStatus(job) {
      if (job.status === 'completed') {
        if (!isNonEmptyString(job.conclusion)) return null;
        return job.conclusion === 'success' ? 'SUCCESS' : 'FAILURE';
      }
      if (job.status === 'in_progress') {
        return 'IN_PROGRESS';
      }

      if (['queued', 'waiting', 'pending', 'requested'].includes(job.status)) {
        return 'QUEUED';
      }

      return null;
    }

    function successfulModel(repository, commitSha, run, job, now, status) {
      return {
        ok: true,
        repository,
        commit_sha: commitSha,
        workflow_name: WORKFLOW_NAME,
        job_name: JOB_NAME,
        run_id: run.id,
        status,
        conclusion: job.conclusion ?? null,
        run_url: isNonEmptyString(run.html_url) ? run.html_url : null,
        fetched_at: fetchedAt(now)
      };
    }

    // Synchronous transport-binding surface for runtimes such as Apps Script.
    // The injected reader performs GET-only JSON transport and returns the same small
    // {ok,data|error} boundary used below. ZASS validation semantics remain outside ASC.
    function readZassCiStatusWithJsonReader({
      repository,
      commitSha,
      readJson: jsonReader,
      now = () => new Date().toISOString()
    } = {}) {
      if (typeof jsonReader !== 'function') {
        return readError(repository, commitSha, now, 'MISSING_READER', 'A JSON reader is required.');
      }

      if (!validateRepository(repository)) {
        return readError(repository, commitSha, now, 'INVALID_REPOSITORY', 'Repository must use owner/repository form.');
      }

      if (!validateCommitSha(commitSha)) {
        return readError(repository, commitSha, now, 'INVALID_COMMIT_SHA', 'Commit SHA must be a full 40-character hexadecimal SHA.');
      }

      const encodedRepository = encodeRepository(repository);
      const runsUrl = API_ROOT + '/repos/' + encodedRepository +
        '/actions/runs?head_sha=' + encodeURIComponent(commitSha) + '&per_page=100';

      const runsResult = jsonReader(runsUrl);
      if (!runsResult || runsResult.ok !== true) {
        const error = runsResult || {};
        return readError(repository, commitSha, now,
          error.code || 'GITHUB_READ_FAILED',
          error.message || 'GitHub workflow-runs read failed.',
          error.httpStatus);
      }

      if (!runsResult.data || !Array.isArray(runsResult.data.workflow_runs)) {
        return readError(repository, commitSha, now, 'MALFORMED_RUNS_RESPONSE', 'GitHub workflow-runs response was malformed.');
      }

      const run = selectWorkflowRun(runsResult.data.workflow_runs, commitSha);
      if (!run) {
        return notFound(repository, commitSha, now);
      }

      const jobsUrl = API_ROOT + '/repos/' + encodedRepository +
        '/actions/runs/' + run.id + '/jobs?filter=latest&per_page=100';
      const jobsResult = jsonReader(jobsUrl);

      if (!jobsResult || jobsResult.ok !== true) {
        const error = jobsResult || {};
        return readError(repository, commitSha, now,
          error.code || 'GITHUB_READ_FAILED',
          error.message || 'GitHub jobs read failed.',
          error.httpStatus);
      }

      if (!jobsResult.data || !Array.isArray(jobsResult.data.jobs)) {
        return readError(repository, commitSha, now, 'MALFORMED_JOBS_RESPONSE', 'GitHub jobs response was malformed.');
      }

      const matchingJobs = jobsResult.data.jobs.filter(function (job) {
        return job && job.name === JOB_NAME;
      });

      if (matchingJobs.length === 0) {
        return notFound(repository, commitSha, now);
      }

      if (matchingJobs.length !== 1) {
        return readError(repository, commitSha, now, 'AMBIGUOUS_ZASS_CI_JOB', 'Multiple matching ZASS CI jobs were returned.');
      }

      const job = matchingJobs[0];
      const status = normalizeJobStatus(job);
      if (!status) {
        return readError(repository, commitSha, now, 'UNSUPPORTED_JOB_STATE', 'ZASS CI job state could not be normalized safely.');
      }

      return successfulModel(repository, commitSha, run, job, now, status);
    }

    function createZassCiStatusConsumer({
      fetchImpl = globalThis.fetch,
      token = null,
      now = () => new Date().toISOString()
    } = {}) {
      async function readStatus({ repository, commitSha } = {}) {
        if (typeof fetchImpl !== 'function') {
          return readError(repository, commitSha, now, 'MISSING_FETCH', 'Fetch implementation is missing.');
        }
        if (!validateRepository(repository)) {
          return readError(repository, commitSha, now, 'INVALID_REPOSITORY', 'Repository must use owner/repository form.');
        }

        if (!validateCommitSha(commitSha)) {
          return readError(repository, commitSha, now, 'INVALID_COMMIT_SHA', 'Commit SHA must be a full 40-character hexadecimal SHA.');
        }

        const headers = createHeaders(token);
        const encodedRepository = encodeRepository(repository);
        const runsUrl = API_ROOT + '/repos/' + encodedRepository +
          '/actions/runs?head_sha=' + encodeURIComponent(commitSha) + '&per_page=100';

        const runsResult = await fetchJson(fetchImpl, runsUrl, headers);
        if (!runsResult.ok) {
          return readError(
            repository,
            commitSha,
            now,
            runsResult.code,
            runsResult.message,
            runsResult.httpStatus
          );
        }

        if (!runsResult.data || !Array.isArray(runsResult.data.workflow_runs)) {
          return readError(repository, commitSha, now, 'MALFORMED_RUNS_RESPONSE', 'GitHub workflow-runs response was malformed.');
        }

        const run = selectWorkflowRun(runsResult.data.workflow_runs, commitSha);
        if (!run) {
          return notFound(repository, commitSha, now);
        }

        const jobsUrl = API_ROOT + '/repos/' + encodedRepository +
          '/actions/runs/' + run.id + '/jobs?filter=latest&per_page=100';
        const jobsResult = await fetchJson(fetchImpl, jobsUrl, headers);

        if (!jobsResult.ok) {
          return readError(
            repository,
            commitSha,
            now,
            jobsResult.code,
            jobsResult.message,
            jobsResult.httpStatus
          );
        }

        if (!jobsResult.data || !Array.isArray(jobsResult.data.jobs)) {
          return readError(repository, commitSha, now, 'MALFORMED_JOBS_RESPONSE', 'GitHub jobs response was malformed.');
        }

        const matchingJobs = jobsResult.data.jobs.filter(function (job) {
          return job && job.name === JOB_NAME;
        });

        if (matchingJobs.length === 0) {
          return notFound(repository, commitSha, now);
        }

        if (matchingJobs.length !== 1) {
          return readError(repository, commitSha, now, 'AMBIGUOUS_ZASS_CI_JOB', 'Multiple matching ZASS CI jobs were returned.');
        }

        const job = matchingJobs[0];
        const status = normalizeJobStatus(job);
        if (!status) {
          return readError(repository, commitSha, now, 'UNSUPPORTED_JOB_STATE', 'ZASS CI job state could not be normalized safely.');
        }

        return successfulModel(repository, commitSha, run, job, now, status);
      }

      return Object.freeze({ readStatus });
    }

    const ZASS_CI_IDENTITY = Object.freeze({
      workflow_name: WORKFLOW_NAME,
      job_name: JOB_NAME
    });

    return Object.freeze({ readZassCiStatusWithJsonReader, createZassCiStatusConsumer, ZASS_CI_IDENTITY });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: continuity/private-continuity-state.mjs ----
  ASC_NS.continuity = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const ULID_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    const ULID_RE = /^[0-9A-HJKMNP-TV-Z]{26}$/;

    function isPlainObject(value) {
      if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
      return Object.prototype.toString.call(value) === '[object Object]';
    }

    function cloneJson(value) {
      return value === undefined ? undefined : JSON.parse(JSON.stringify(value));
    }

    function canonicalJson(value) {
      if (value === null) return 'null';
      if (typeof value === 'string') return JSON.stringify(value);
      if (typeof value === 'boolean') return value ? 'true' : 'false';
      if (typeof value === 'number') {
        if (!Number.isFinite(value)) throw new TypeError('Non-finite numbers are not supported.');
        return JSON.stringify(value);
      }
      if (Array.isArray(value)) {
        return '[' + value.map(canonicalJson).join(',') + ']';
      }
      if (isPlainObject(value)) {
        return '{' + Object.keys(value).sort().map(function (key) {
          const item = value[key];
          if (item === undefined || typeof item === 'function' || typeof item === 'symbol') {
            throw new TypeError('Unsupported JSON value.');
          }
          return JSON.stringify(key) + ':' + canonicalJson(item);
        }).join(',') + '}';
      }
      throw new TypeError('Only JSON-compatible values are supported.');
    }

    function assertProjectId(projectId) {
      if (typeof projectId !== 'string' || projectId.length < 1 || projectId.length > 128 || /[\u0000-\u001f]/.test(projectId)) {
        throw new TypeError('projectId must be a non-empty stable identifier.');
      }
    }

    function assertPrefixedUlid(value, prefix, fieldName) {
      if (typeof value !== 'string' || !value.startsWith(prefix) || !ULID_RE.test(value.slice(prefix.length))) {
        throw new TypeError(fieldName + ' must use ' + prefix + '<ULID>.');
      }
    }

    function assertRequestId(requestId) {
      assertPrefixedUlid(requestId, 'req_', 'requestId');
    }

    function assertThreadId(threadId) {
      assertPrefixedUlid(threadId, 'th_', 'threadId');
    }

    function assertRevision(revision) {
      if (!Number.isSafeInteger(revision) || revision < 1) {
        throw new TypeError('expectedRevision must be a positive integer.');
      }
    }

    function assertOperation(operation) {
      if (typeof operation !== 'string' || operation.length < 1 || operation.length > 128) {
        throw new TypeError('operation must be a non-empty string.');
      }
    }

    function assertSemanticRecord(record) {
      if (!isPlainObject(record)) {
        throw new TypeError('semanticRecord must be a plain JSON object.');
      }
      canonicalJson(record);
    }

    function assertChanges(changes) {
      if (!isPlainObject(changes)) {
        throw new TypeError('changes must be a plain JSON object.');
      }
      canonicalJson(changes);
    }

    function encodeTime(timeMs) {
      let value = Math.floor(timeMs);
      let output = '';
      for (let i = 0; i < 10; i += 1) {
        output = ULID_ALPHABET[value % 32] + output;
        value = Math.floor(value / 32);
      }
      return output;
    }

    function randomUlidPart(random) {
      let output = '';
      for (let i = 0; i < 16; i += 1) {
        const value = Math.floor(random() * 32);
        if (value < 0 || value > 31 || !Number.isFinite(value)) {
          throw new Error('Random source returned an invalid value.');
        }
        output += ULID_ALPHABET[value];
      }
      return output;
    }

    function defaultIdFactory(prefix, nowMs, random) {
      return prefix + encodeTime(nowMs()) + randomUlidPart(random);
    }

    function createEmptyPrivateContinuityState() {
      return {
        schema_version: '0.1',
        projects: {}
      };
    }

    function createInMemoryPrivateContinuityStore(initialState = createEmptyPrivateContinuityState()) {
      let state = cloneJson(initialState);

      return {
        read() {
          return cloneJson(state);
        },
        transact(mutator) {
          if (typeof mutator !== 'function') throw new TypeError('mutator is required.');
          const working = cloneJson(state);
          const outcome = mutator(working);
          if (!outcome || typeof outcome !== 'object' || !('result' in outcome)) {
            throw new Error('Transaction mutator must return { result, changed }.');
          }
          if (outcome.changed === true) {
            state = working;
          }
          return cloneJson(outcome.result);
        }
      };
    }

    function projectState(state, projectId) {
      return state.projects[projectId] || null;
    }

    function ensureProject(state, projectId) {
      if (!state.projects[projectId]) {
        state.projects[projectId] = {
          project_id: projectId,
          threads: {},
          events: {},
          tombstones: {},
          requests: {}
        };
      }
      return state.projects[projectId];
    }

    function requestFingerprint(fingerprint, payload) {
      const digest = fingerprint(canonicalJson(payload));
      if (typeof digest !== 'string' || digest.length < 8) {
        throw new Error('fingerprint() must return a stable non-empty string.');
      }
      return digest;
    }

    function duplicateResult(existing, fingerprintValue) {
      if (!existing) return null;
      if (existing.payload_fingerprint !== fingerprintValue) {
        return {
          status: 'IDEMPOTENCY_KEY_REUSE_CONFLICT',
          request_id: existing.request_id
        };
      }
      return {
        status: 'ALREADY_APPLIED',
        request_id: existing.request_id,
        original_result: cloneJson(existing.result)
      };
    }

    function makeRecord({ projectId, threadId, revision, createdAt, updatedAt, semanticRecord }) {
      return {
        project_id: projectId,
        thread_id: threadId,
        revision,
        created_at: createdAt,
        semantic_updated_at: updatedAt,
        semantic_record: cloneJson(semanticRecord)
      };
    }

    function makeEvent({ eventId, threadId, revision, operation, occurredAt, change }) {
      return {
        event_id: eventId,
        thread_id: threadId,
        revision,
        event_type: operation,
        occurred_at: occurredAt,
        change: cloneJson(change)
      };
    }

    function safeNow(now) {
      const value = now();
      if (typeof value !== 'string' || Number.isNaN(Date.parse(value))) {
        throw new Error('now() must return an ISO date-time string.');
      }
      return value;
    }

    function createPrivateContinuityService({
      store,
      fingerprint,
      now = () => new Date().toISOString(),
      nowMs = () => Date.now(),
      random = () => Math.random(),
      newThreadId,
      newEventId
    } = {}) {
      if (!store || typeof store.read !== 'function' || typeof store.transact !== 'function') {
        throw new TypeError('store must provide read() and transact().');
      }
      if (typeof fingerprint !== 'function') {
        throw new TypeError('fingerprint function is required.');
      }

      const threadIdFactory = typeof newThreadId === 'function'
        ? newThreadId
        : () => defaultIdFactory('th_', nowMs, random);
      const eventIdFactory = typeof newEventId === 'function'
        ? newEventId
        : () => defaultIdFactory('ev_', nowMs, random);

      function getThread({ projectId, threadId }) {
        assertProjectId(projectId);
        assertThreadId(threadId);
        const state = store.read();
        const project = projectState(state, projectId);
        if (!project) {
          return { status: 'NOT_FOUND', project_id: projectId, thread_id: threadId };
        }
        if (project.tombstones[threadId]) {
          return {
            status: 'THREAD_TOMBSTONED',
            project_id: projectId,
            thread_id: threadId,
            tombstone: cloneJson(project.tombstones[threadId])
          };
        }
        const record = project.threads[threadId];
        if (!record) {
          return { status: 'NOT_FOUND', project_id: projectId, thread_id: threadId };
        }
        return {
          status: 'FOUND',
          project_id: projectId,
          thread_id: threadId,
          revision: record.revision,
          record: cloneJson(record)
        };
      }

      function listThreads({ projectId }) {
        assertProjectId(projectId);
        const state = store.read();
        const project = projectState(state, projectId);
        if (!project) return [];
        return Object.values(project.threads)
          .map(function (record) {
            return {
              project_id: projectId,
              thread_id: record.thread_id,
              revision: record.revision,
              created_at: record.created_at,
              semantic_updated_at: record.semantic_updated_at
            };
          })
          .sort(function (a, b) {
            return a.thread_id.localeCompare(b.thread_id);
          });
      }

      function readEvents({ projectId, threadId }) {
        assertProjectId(projectId);
        assertThreadId(threadId);
        const state = store.read();
        const project = projectState(state, projectId);
        if (!project) return [];
        if (project.tombstones[threadId]) return [];
        return cloneJson(project.events[threadId] || []);
      }

      function bootstrap({
        projectId,
        requestId,
        resolution,
        semanticRecord
      }) {
        assertProjectId(projectId);
        if (!resolution || typeof resolution !== 'object' || typeof resolution.status !== 'string') {
          throw new TypeError('resolution with explicit status is required.');
        }

        if (resolution.status === 'MULTIPLE_MATCHES') {
          return {
            status: 'NEEDS_CLARIFICATION',
            project_id: projectId,
            candidate_thread_ids: Array.isArray(resolution.candidate_thread_ids)
              ? cloneJson(resolution.candidate_thread_ids)
              : []
          };
        }

        if (resolution.status === 'UNIQUE_MATCH') {
          assertThreadId(resolution.thread_id);
          const current = getThread({ projectId, threadId: resolution.thread_id });
          if (current.status === 'FOUND') {
            return {
              status: 'ATTACHED_EXISTING',
              project_id: projectId,
              thread_id: resolution.thread_id,
              revision: current.revision
            };
          }
          return current.status === 'THREAD_TOMBSTONED'
            ? current
            : {
                status: 'RESOLUTION_TARGET_NOT_FOUND',
                project_id: projectId,
                thread_id: resolution.thread_id
              };
        }

        if (resolution.status !== 'NO_MATCH') {
          return {
            status: 'UNSUPPORTED_RESOLUTION',
            project_id: projectId,
            resolution_status: resolution.status
          };
        }

        assertRequestId(requestId);
        assertSemanticRecord(semanticRecord);

        const payload = {
          project_id: projectId,
          request_id: requestId,
          resolution: { status: 'NO_MATCH' },
          semantic_record: semanticRecord
        };
        const payloadFingerprint = requestFingerprint(fingerprint, payload);

        return store.transact(function (state) {
          const project = ensureProject(state, projectId);
          const duplicate = duplicateResult(project.requests[requestId], payloadFingerprint);
          if (duplicate) return { result: duplicate, changed: false };

          const threadId = threadIdFactory();
          assertThreadId(threadId);
          if (project.threads[threadId] || project.tombstones[threadId]) {
            throw new Error('Generated thread identity collision.');
          }

          const eventId = eventIdFactory();
          assertPrefixedUlid(eventId, 'ev_', 'eventId');
          const timestamp = safeNow(now);
          const record = makeRecord({
            projectId,
            threadId,
            revision: 1,
            createdAt: timestamp,
            updatedAt: timestamp,
            semanticRecord
          });
          const event = makeEvent({
            eventId,
            threadId,
            revision: 1,
            operation: 'CREATE',
            occurredAt: timestamp,
            change: semanticRecord
          });

          project.threads[threadId] = record;
          project.events[threadId] = [event];

          const result = {
            status: 'CREATED',
            project_id: projectId,
            request_id: requestId,
            thread_id: threadId,
            revision: 1,
            event_id: eventId
          };
          project.requests[requestId] = {
            request_id: requestId,
            thread_id: threadId,
            payload_fingerprint: payloadFingerprint,
            result: cloneJson(result)
          };

          return { result, changed: true };
        });
      }

      function applyMutation({
        projectId,
        requestId,
        threadId,
        expectedRevision,
        operation,
        changes,
        nextSemanticRecord
      }) {
        assertProjectId(projectId);
        assertRequestId(requestId);
        assertThreadId(threadId);
        assertRevision(expectedRevision);
        assertOperation(operation);
        assertChanges(changes);
        assertSemanticRecord(nextSemanticRecord);

        const payload = {
          project_id: projectId,
          request_id: requestId,
          thread_id: threadId,
          expected_revision: expectedRevision,
          operation,
          changes,
          next_semantic_record: nextSemanticRecord
        };
        const payloadFingerprint = requestFingerprint(fingerprint, payload);

        return store.transact(function (state) {
          const project = projectState(state, projectId);
          if (!project) {
            return {
              result: { status: 'NOT_FOUND', project_id: projectId, thread_id: threadId },
              changed: false
            };
          }

          const duplicate = duplicateResult(project.requests[requestId], payloadFingerprint);
          if (duplicate) return { result: duplicate, changed: false };

          if (project.tombstones[threadId]) {
            return {
              result: {
                status: 'THREAD_TOMBSTONED',
                project_id: projectId,
                thread_id: threadId,
                tombstone: cloneJson(project.tombstones[threadId])
              },
              changed: false
            };
          }

          const current = project.threads[threadId];
          if (!current) {
            return {
              result: { status: 'NOT_FOUND', project_id: projectId, thread_id: threadId },
              changed: false
            };
          }

          if (current.revision !== expectedRevision) {
            return {
              result: {
                status: 'REVISION_CONFLICT',
                project_id: projectId,
                thread_id: threadId,
                expected_revision: expectedRevision,
                current_revision: current.revision
              },
              changed: false
            };
          }

          const revision = current.revision + 1;
          const timestamp = safeNow(now);
          const eventId = eventIdFactory();
          assertPrefixedUlid(eventId, 'ev_', 'eventId');

          project.threads[threadId] = makeRecord({
            projectId,
            threadId,
            revision,
            createdAt: current.created_at,
            updatedAt: timestamp,
            semanticRecord: nextSemanticRecord
          });
          if (!Array.isArray(project.events[threadId])) project.events[threadId] = [];
          project.events[threadId].push(makeEvent({
            eventId,
            threadId,
            revision,
            operation,
            occurredAt: timestamp,
            change: changes
          }));

          const result = {
            status: 'APPLIED',
            project_id: projectId,
            request_id: requestId,
            thread_id: threadId,
            revision,
            event_id: eventId,
            operation
          };
          project.requests[requestId] = {
            request_id: requestId,
            thread_id: threadId,
            payload_fingerprint: payloadFingerprint,
            result: cloneJson(result)
          };

          return { result, changed: true };
        });
      }

      function deleteThread({
        projectId,
        requestId,
        threadId,
        expectedRevision
      }) {
        assertProjectId(projectId);
        assertRequestId(requestId);
        assertThreadId(threadId);
        assertRevision(expectedRevision);

        const payload = {
          project_id: projectId,
          request_id: requestId,
          thread_id: threadId,
          expected_revision: expectedRevision,
          operation: 'DELETE_THREAD'
        };
        const payloadFingerprint = requestFingerprint(fingerprint, payload);

        return store.transact(function (state) {
          const project = projectState(state, projectId);
          if (!project) {
            return {
              result: { status: 'NOT_FOUND', project_id: projectId, thread_id: threadId },
              changed: false
            };
          }

          const duplicate = duplicateResult(project.requests[requestId], payloadFingerprint);
          if (duplicate) return { result: duplicate, changed: false };

          if (project.tombstones[threadId]) {
            return {
              result: {
                status: 'THREAD_TOMBSTONED',
                project_id: projectId,
                thread_id: threadId,
                tombstone: cloneJson(project.tombstones[threadId])
              },
              changed: false
            };
          }

          const current = project.threads[threadId];
          if (!current) {
            return {
              result: { status: 'NOT_FOUND', project_id: projectId, thread_id: threadId },
              changed: false
            };
          }

          if (current.revision !== expectedRevision) {
            return {
              result: {
                status: 'REVISION_CONFLICT',
                project_id: projectId,
                thread_id: threadId,
                expected_revision: expectedRevision,
                current_revision: current.revision
              },
              changed: false
            };
          }

          const timestamp = safeNow(now);
          delete project.threads[threadId];
          delete project.events[threadId];

          Object.keys(project.requests).forEach(function (key) {
            if (project.requests[key] && project.requests[key].thread_id === threadId) {
              delete project.requests[key];
            }
          });

          project.tombstones[threadId] = {
            thread_id: threadId,
            deleted_at: timestamp,
            deletion_request_id: requestId
          };

          const result = {
            status: 'DELETED',
            project_id: projectId,
            request_id: requestId,
            thread_id: threadId,
            deleted_at: timestamp
          };
          project.requests[requestId] = {
            request_id: requestId,
            thread_id: threadId,
            payload_fingerprint: payloadFingerprint,
            result: cloneJson(result)
          };

          return { result, changed: true };
        });
      }

      return Object.freeze({
        getThread,
        listThreads,
        readEvents,
        bootstrap,
        applyMutation,
        deleteThread
      });
    }

    const PRIVATE_CONTINUITY_STATE_VERSION = '0.1';

    return Object.freeze({ createEmptyPrivateContinuityState, createInMemoryPrivateContinuityStore, createPrivateContinuityService, PRIVATE_CONTINUITY_STATE_VERSION });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: continuity/index-freshness.mjs ----
  ASC_NS.indexFreshness = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    function validRepository(value) {
      return typeof value === 'string' && /^[^/\s]+\/[^/\s]+$/.test(value);
    }

    function validRef(value) {
      return typeof value === 'string' && value.length > 0 && value.length <= 255 && !/[\u0000-\u001f]/.test(value);
    }

    function validCommit(value) {
      return typeof value === 'string' && /^[0-9a-f]{40}$/i.test(value);
    }

    function checkedAtValue(checkedAt) {
      if (typeof checkedAt !== 'string' || Number.isNaN(Date.parse(checkedAt))) return null;
      return checkedAt;
    }

    function assessIndexFreshness({
      canonicalRepository,
      canonicalRef,
      canonicalCommit,
      indexedRepository,
      indexedRef,
      indexedCommit,
      checkedAt
    } = {}) {
      const base = {
        canonical_repository: validRepository(canonicalRepository) ? canonicalRepository : null,
        canonical_ref: validRef(canonicalRef) ? canonicalRef : null,
        canonical_commit: validCommit(canonicalCommit) ? canonicalCommit.toLowerCase() : null,
        indexed_repository: validRepository(indexedRepository) ? indexedRepository : null,
        indexed_ref: validRef(indexedRef) ? indexedRef : null,
        indexed_commit: validCommit(indexedCommit) ? indexedCommit.toLowerCase() : null,
        checked_at: checkedAtValue(checkedAt)
      };

      if (
        !base.canonical_repository ||
        !base.canonical_ref ||
        !base.canonical_commit ||
        !base.indexed_repository ||
        !base.indexed_ref ||
        !base.indexed_commit ||
        !base.checked_at
      ) {
        return {
          ...base,
          status: 'UNVERIFIED',
          reason: 'MISSING_OR_INVALID_SOURCE_EVIDENCE'
        };
      }

      if (
        base.canonical_repository !== base.indexed_repository ||
        base.canonical_ref !== base.indexed_ref
      ) {
        return {
          ...base,
          status: 'SOURCE_MISMATCH',
          reason: 'INDEX_POINTS_TO_DIFFERENT_SOURCE'
        };
      }

      if (base.canonical_commit === base.indexed_commit) {
        return {
          ...base,
          status: 'CURRENT',
          reason: 'EXACT_COMMIT_MATCH'
        };
      }

      return {
        ...base,
        status: 'STALE',
        reason: 'CANONICAL_HEAD_DIFFERS_FROM_INDEXED_COMMIT'
      };
    }

    return Object.freeze({ assessIndexFreshness });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: continuity/github-source-head.mjs ----
  ASC_NS.sourceHead = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const API_ROOT = 'https://api.github.com';

    function validRepository(repository) {
      return typeof repository === 'string' && /^[^/\s]+\/[^/\s]+$/.test(repository);
    }

    function validCommit(commit) {
      return typeof commit === 'string' && /^[0-9a-f]{40}$/i.test(commit);
    }

    function fetchedAt(now) {
      try {
        const value = now();
        return typeof value === 'string' && !Number.isNaN(Date.parse(value)) ? value : null;
      } catch (_error) {
        return null;
      }
    }

    function readError(repository, now, code, message, extra) {
      return {
        ok: false,
        repository: validRepository(repository) ? repository : null,
        ref: null,
        commit_sha: null,
        fetched_at: fetchedAt(now),
        error: {
          code,
          message,
          ...(extra || {})
        }
      };
    }

    function readGitHubDefaultHeadWithJsonReader({
      repository,
      readJson,
      now = () => new Date().toISOString()
    } = {}) {
      if (!validRepository(repository)) {
        return readError(repository, now, 'INVALID_REPOSITORY', 'Repository must use owner/repository form.');
      }
      if (typeof readJson !== 'function') {
        return readError(repository, now, 'MISSING_READER', 'A JSON reader is required.');
      }

      const encoded = repository.split('/').map(encodeURIComponent).join('/');
      const repoResult = readJson(API_ROOT + '/repos/' + encoded);
      if (!repoResult || repoResult.ok !== true) {
        const error = repoResult || {};
        return readError(
          repository,
          now,
          error.code || 'GITHUB_READ_FAILED',
          error.message || 'Repository metadata could not be read.',
          typeof error.httpStatus === 'number' ? { http_status: error.httpStatus } : undefined
        );
      }

      const defaultBranch = repoResult.data && repoResult.data.default_branch;
      if (typeof defaultBranch !== 'string' || defaultBranch.length === 0) {
        return readError(repository, now, 'MALFORMED_REPOSITORY_RESPONSE', 'Repository default_branch is missing.');
      }

      const commitResult = readJson(
        API_ROOT + '/repos/' + encoded + '/commits/' + encodeURIComponent(defaultBranch)
      );
      if (!commitResult || commitResult.ok !== true) {
        const error = commitResult || {};
        const result = readError(
          repository,
          now,
          error.code || 'GITHUB_READ_FAILED',
          error.message || 'Canonical branch head could not be read.',
          typeof error.httpStatus === 'number' ? { http_status: error.httpStatus } : undefined
        );
        result.ref = defaultBranch;
        return result;
      }

      const sha = commitResult.data && commitResult.data.sha;
      if (!validCommit(sha)) {
        const result = readError(repository, now, 'MALFORMED_COMMIT_RESPONSE', 'Canonical branch head SHA is missing or invalid.');
        result.ref = defaultBranch;
        return result;
      }

      return {
        ok: true,
        repository,
        ref: defaultBranch,
        commit_sha: sha.toLowerCase(),
        fetched_at: fetchedAt(now)
      };
    }

    return Object.freeze({ readGitHubDefaultHeadWithJsonReader });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: receipts/write-receipt.mjs ----
  ASC_NS.receipts = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    const SUCCESS_OUTCOMES = new Set(['VERIFIED_WRITE', 'NO_CHANGE']);
    const FAILURE_OUTCOMES = new Set([
      'READ_ERROR',
      'WRITE_ERROR',
      'WRITE_UNVERIFIED',
      'INVALID_INPUT'
    ]);
    const HISTORY_FIELDS = Object.freeze([
      'request_id',
      'project_id',
      'operation',
      'destination',
      'status',
      'affected_resource',
      'commit_or_record_id',
      'source_commit',
      'timestamp',
      'failure_reason',
      'receipt_json'
    ]);

    function cloneValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function invalidResult(errors) {
      return {
        ok: false,
        outcome: 'INVALID_RECEIPT_INPUT',
        errors
      };
    }

    function validateReceiptInput(input) {
      const errors = [];

      if (!input || typeof input !== 'object') {
        return invalidResult([{ code: 'INVALID_INPUT', message: 'Receipt input must be an object.' }]);
      }

      ['requestId', 'projectId', 'operation', 'timestamp'].forEach(function (field) {
        if (!isNonEmptyString(input[field])) {
          errors.push({ code: 'INVALID_' + field.toUpperCase(), message: field + ' must be a non-empty string.' });
        }
      });

      const adapterResult = input.adapterResult;
      if (!adapterResult || typeof adapterResult !== 'object') {
        errors.push({ code: 'INVALID_ADAPTER_RESULT', message: 'Adapter result is required.' });
      } else if (!SUCCESS_OUTCOMES.has(adapterResult.outcome) && !FAILURE_OUTCOMES.has(adapterResult.outcome)) {
        errors.push({ code: 'UNKNOWN_ADAPTER_OUTCOME', message: 'Adapter outcome is not recognized.' });
      }

      return errors.length === 0 ? null : invalidResult(errors);
    }

    function affectedResource(adapterResult) {
      if (isNonEmptyString(adapterResult.repository) && isNonEmptyString(adapterResult.path)) {
        return adapterResult.repository + '/' + adapterResult.path;
      }

      return null;
    }

    function failureReason(adapterResult) {
      if (adapterResult.error && isNonEmptyString(adapterResult.error.message)) {
        return adapterResult.error.message;
      }

      if (adapterResult.outcome === 'WRITE_UNVERIFIED') {
        return 'Adapter write was not verified as persisted.';
      }

      return adapterResult.outcome;
    }

    function buildReceipt(input) {
      const adapterResult = cloneValue(input.adapterResult);
      const status = SUCCESS_OUTCOMES.has(adapterResult.outcome) ? 'SUCCESS' : 'FAILED';
      const receipt = {
        receipt_version: '0.1',
        request_id: input.requestId,
        project_id: input.projectId,
        operation: input.operation,
        destination: adapterResult.destination || null,
        status,
        affected_resource: affectedResource(adapterResult),
        commit_or_record_id: adapterResult.commitSha || null,
        source_commit: input.sourceCommit || null,
        timestamp: input.timestamp,
        failure_reason: status === 'FAILED' ? failureReason(adapterResult) : null,
        adapter_outcome: adapterResult.outcome,
        write_performed: adapterResult.writePerformed === true,
        verified: adapterResult.verified === true
      };

      return receipt;
    }

    function createWriteReceipt(input) {
      const validation = validateReceiptInput(input);
      if (validation) {
        return validation;
      }

      const receipt = buildReceipt(input);
      return {
        ok: true,
        outcome: 'RECEIPT_CREATED',
        receipt: cloneValue(receipt),
        historyEntry: createHistoryEntry(receipt)
      };
    }

    function createHistoryEntry(receipt) {
      const historyEntry = {
        request_id: receipt.request_id,
        project_id: receipt.project_id,
        operation: receipt.operation,
        destination: receipt.destination,
        status: receipt.status,
        affected_resource: receipt.affected_resource,
        commit_or_record_id: receipt.commit_or_record_id,
        source_commit: receipt.source_commit,
        timestamp: receipt.timestamp,
        failure_reason: receipt.failure_reason,
        receipt_json: JSON.stringify(receipt)
      };

      return HISTORY_FIELDS.reduce(function (entry, field) {
        entry[field] = historyEntry[field];
        return entry;
      }, {});
    }

    async function persistHistory(receiptResult, historyWriter) {
      if (!receiptResult || receiptResult.ok !== true || !receiptResult.historyEntry) {
        return {
          ok: false,
          outcome: 'HISTORY_NOT_ATTEMPTED',
          error: { code: 'INVALID_RECEIPT', message: 'A created receipt is required.' }
        };
      }

      if (!historyWriter || typeof historyWriter.appendHistory !== 'function') {
        return {
          ok: false,
          outcome: 'HISTORY_WRITE_FAILED',
          error: { code: 'INVALID_HISTORY_WRITER', message: 'An injected HISTORY writer is required.' }
        };
      }

      try {
        await historyWriter.appendHistory(cloneValue(receiptResult.historyEntry));
        return {
          ok: true,
          outcome: 'HISTORY_PERSISTED',
          receipt: cloneValue(receiptResult.receipt),
          historyEntry: cloneValue(receiptResult.historyEntry)
        };
      } catch (error) {
        return {
          ok: false,
          outcome: 'HISTORY_WRITE_FAILED',
          receipt: cloneValue(receiptResult.receipt),
          error: { code: 'HISTORY_WRITER_ERROR', message: 'HISTORY writer failed.' }
        };
      }
    }


    return Object.freeze({ createWriteReceipt, createHistoryEntry, persistHistory, HISTORY_FIELDS });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);

  // ---- module: flow/confirm-sync.mjs ----
  ASC_NS.flow = (function (Buffer, atob, btoa, TextEncoder, TextDecoder) {
    'use strict';
    // T-008A — runtime-neutral preview → CONFIRM & SYNC → write/verify → receipt → HISTORY → redirect decision.
    //
    // This module only composes existing owners:
    //   - ASC Core (T-005)          validate / authorize / route
    //   - GitHub adapter (T-006)    read → write → read verification
    //   - Receipt + HISTORY (T-007) factual receipt and injected HISTORY persistence
    // It performs no I/O itself. All destination clients, HISTORY writers, clocks,
    // authorization policies, write-spec resolution, and the main ASC UI URL are injected.

    const { processCoreRequest } = ASC_NS.core;
    const { runGitHubAdapter } = ASC_NS.githubAdapter;
    const { createWriteReceipt, persistHistory } = ASC_NS.receipts;
    const { validateEnvelopeSecurity } = ASC_NS.security;
    const CONFIRM_ACTION = 'CONFIRM_AND_SYNC';

    // v0.1 slice: only the GitHub adapter exists. Any other destination set fails closed
    // before any write so no partial persistence can occur.
    const SUPPORTED_DESTINATION_SETS = Object.freeze([['GitHub']]);

    function cloneValue(value) {
      if (Array.isArray(value)) {
        return value.map(cloneValue);
      }

      if (value !== null && typeof value === 'object') {
        return Object.keys(value).reduce(function (copy, key) {
          copy[key] = cloneValue(value[key]);
          return copy;
        }, {});
      }

      return value;
    }

    function isNonEmptyString(value) {
      return typeof value === 'string' && value.length > 0;
    }

    function failed(stage, code, message, extra) {
      return {
        state: 'FAILED',
        stage,
        redirect: null,
        error: { code, message },
        ...(extra || {})
      };
    }

    function readEnvelope(envelope) {
      if (!envelope || typeof envelope !== 'object' || Array.isArray(envelope)) {
        return { error: failed('PREVIEW', 'INVALID_ENVELOPE', 'A decoded ASC envelope is required.') };
      }

      if (!isNonEmptyString(envelope.request_id)) {
        return { error: failed('PREVIEW', 'MISSING_REQUEST_ID', 'Envelope request_id is required.') };
      }

      return { requestId: envelope.request_id, contract: envelope.contract };
    }

    // Explicit confirmation must be an affirmative CONFIRM & SYNC action bound to this request.
    function isExplicitConfirmation(confirmation, requestId) {
      return Boolean(confirmation) &&
        typeof confirmation === 'object' &&
        confirmation.confirmed === true &&
        confirmation.action === CONFIRM_ACTION &&
        confirmation.requestId === requestId;
    }

    // T-010 (D-029) security gate: envelope structure, expiry/lifetime, SHA-256 integrity.
    function securityGate(envelope, requestId, now, sha256Hex) {
      const security = validateEnvelopeSecurity(envelope, { now, sha256Hex });
      if (!security.ok) {
        return {
          error: failed('SECURITY', security.code, security.message, {
            requestId: requestId || null,
            writePerformed: false
          })
        };
      }
      return { security };
    }

    // Owner identity reuses the injected v0.1 owner policy (no parallel user system).
    function ownerGate(verifyOwner, authorizationContext, requestId) {
      let owner = false;
      try {
        owner = verifyOwner(authorizationContext) === true;
      } catch (error) {
        owner = false;
      }
      if (!owner) {
        return failed('OWNER', 'OWNER_REQUIRED', 'Active user is missing or is not the deploying owner.', {
          requestId,
          writePerformed: false
        });
      }
      return null;
    }

    function awaitingConfirmation(read, security) {
      return {
        state: 'AWAITING_CONFIRMATION',
        stage: 'PREVIEW',
        redirect: null,
        requestId: read.requestId,
        contract: cloneValue(read.contract),
        confirmAction: CONFIRM_ACTION,
        security: {
          verified: true,
          algorithm: security.algorithm,
          issuedAt: security.issuedAt,
          expiresAt: security.expiresAt
        },
        writePerformed: false
      };
    }

    // Preview is pure: it validates security + owner but never claims replay state and never
    // touches a destination client or HISTORY writer.
    function previewRequest(envelope, { now, sha256Hex, authorizationContext, verifyOwner } = {}) {
      const read = readEnvelope(envelope);
      if (read.error) {
        return read.error;
      }

      const gate = securityGate(envelope, read.requestId, now, sha256Hex);
      if (gate.error) {
        return gate.error;
      }

      if (typeof verifyOwner !== 'function') {
        return failed('CONFIG', 'MISSING_OWNER_POLICY', 'A server-side owner identity check is required.', {
          requestId: read.requestId,
          writePerformed: false
        });
      }
      const ownerError = ownerGate(verifyOwner, authorizationContext, read.requestId);
      if (ownerError) {
        return ownerError;
      }

      return awaitingConfirmation(read, gate.security);
    }

    function isSupportedDestinationSet(routes) {
      const destinations = routes.map(function (route) { return route.destination; });
      return SUPPORTED_DESTINATION_SETS.some(function (set) {
        return set.length === destinations.length && set.every(function (d, i) { return destinations[i] === d; });
      });
    }

    // T-007 persistHistory treats only a thrown error as writer failure, while the Apps Script
    // History.gs writer reports failure as a returned { ok: false } value. Bridge both without
    // changing either owner: an explicit ok:false result is surfaced as a writer failure.
    function strictHistoryWriter(historyWriter) {
      if (!historyWriter || typeof historyWriter.appendHistory !== 'function') {
        return historyWriter;
      }

      return {
        appendHistory: async function (entry) {
          const result = await historyWriter.appendHistory(entry);
          if (result && typeof result === 'object' && result.ok === false) {
            throw new Error('HISTORY writer reported failure.');
          }
          return result;
        }
      };
    }

    function isValidRedirectUrl(url) {
      return isNonEmptyString(url) && /^https:\/\/[^\s]+$/.test(url);
    }

    async function confirmAndSyncRequest({
      envelope,
      confirmation,
      authorizationContext,
      authorizationPolicy,
      resolveGitHubWriteSpec,
      githubClient,
      historyWriter,
      now,
      sha256Hex,
      verifyOwner,
      claimReplay,
      sourceCommit = null,
      mainUiUrl
    } = {}) {
      const read = readEnvelope(envelope);
      if (read.error) {
        return read.error;
      }

      // Server configuration is checked first so a misconfigured server never consumes a request ID.
      const configError = function (code, message) {
        return failed('CONFIG', code, message, { requestId: read.requestId, writePerformed: false });
      };
      if (typeof now !== 'function') {
        return configError('MISSING_CLOCK', 'A server clock is required for expiry checks and factual receipt timestamps.');
      }
      if (typeof resolveGitHubWriteSpec !== 'function') {
        return configError('MISSING_WRITE_SPEC_RESOLVER', 'A server-side GitHub write-spec resolver is required.');
      }
      if (typeof verifyOwner !== 'function') {
        return configError('MISSING_OWNER_POLICY', 'A server-side owner identity check is required.');
      }
      if (typeof claimReplay !== 'function') {
        return configError('MISSING_REPLAY_GUARD', 'A server-side replay claim is required.');
      }

      // Gate 1 (T-010): security is re-validated at confirm time; a previous preview is never trusted.
      const gate = securityGate(envelope, read.requestId, now, sha256Hex);
      if (gate.error) {
        return gate.error;
      }

      // Gate 2: no persistence of any kind without explicit, request-bound confirmation.
      if (!isExplicitConfirmation(confirmation, read.requestId)) {
        return {
          ...awaitingConfirmation(read, gate.security),
          error: { code: 'CONFIRMATION_REQUIRED', message: 'Explicit CONFIRM & SYNC is required before persistence.' }
        };
      }

      // Gate 3 (T-010): owner identity before replay claim and before any destination I/O.
      const ownerError = ownerGate(verifyOwner, authorizationContext, read.requestId);
      if (ownerError) {
        return ownerError;
      }

      // Gate 4 (T-010): atomic one-time replay claim. Once claimed, the request ID stays
      // consumed even if the destination attempt later fails; a retry needs a new request_id.
      let claim;
      try {
        claim = await claimReplay(read.requestId);
      } catch (error) {
        claim = null;
      }
      if (!claim || claim.claimed !== true) {
        const rejected = Boolean(claim) && claim.code === 'REPLAY_REJECTED';
        return failed('REPLAY', rejected ? 'REPLAY_REJECTED' : 'REPLAY_STORE_UNAVAILABLE',
          rejected
            ? 'This request_id has already been used for a confirmed sync attempt. A new ASC request is required.'
            : 'Replay state could not be safely claimed. Sync was not started; nothing was saved.', {
            requestId: read.requestId,
            writePerformed: false
          });
      }

      // Gate 5: ASC Core validate / authorize / route. Rejection stops before any write.
      const core = processCoreRequest({
        contract: read.contract,
        authorizationContext,
        authorizationPolicy
      });

      if (core.status !== 'ACCEPTED') {
        return failed('CORE', 'CORE_REJECTED', 'ASC Core rejected the request at ' + core.stage + '.', {
          requestId: read.requestId,
          writePerformed: false,
          core: cloneValue(core)
        });
      }

      if (!isSupportedDestinationSet(core.routes)) {
        return failed('ROUTING', 'UNSUPPORTED_DESTINATION_SET', 'This v0.1 flow supports only Destination ["GitHub"].', {
          requestId: read.requestId,
          writePerformed: false
        });
      }

      const invocation = core.adapterInvocations[0];
      let writeSpec;
      try {
        writeSpec = resolveGitHubWriteSpec(cloneValue(invocation));
      } catch (error) {
        writeSpec = null;
      }

      // Gate 6: GitHub adapter owns read → write → read verification.
      const adapterResult = await runGitHubAdapter(invocation, writeSpec, githubClient);

      // Gate 7: T-007 factual receipt.
      const receiptResult = createWriteReceipt({
        requestId: read.requestId,
        projectId: read.contract.Project,
        operation: read.contract.Operation,
        sourceCommit,
        timestamp: now(),
        adapterResult
      });

      if (!receiptResult.ok) {
        return failed('RECEIPT', 'RECEIPT_NOT_CREATED', 'A factual receipt could not be created.', {
          requestId: read.requestId,
          writePerformed: adapterResult.writePerformed === true,
          adapterOutcome: adapterResult.outcome,
          receiptErrors: cloneValue(receiptResult.errors)
        });
      }

      // Gate 8: T-007 HISTORY persistence for both SUCCESS and FAILED receipts.
      const history = await persistHistory(receiptResult, strictHistoryWriter(historyWriter));
      const receipt = cloneValue(receiptResult.receipt);
      const base = {
        requestId: read.requestId,
        receipt,
        historyOutcome: history.outcome,
        writePerformed: receipt.write_performed
      };

      if (receipt.status !== 'SUCCESS' || receipt.verified !== true) {
        return failed('WRITE', 'WRITE_NOT_VERIFIED', receipt.failure_reason || 'Write was not verified.', base);
      }

      if (history.ok !== true) {
        return failed('HISTORY', 'HISTORY_NOT_PERSISTED', 'Verified write receipt exists but HISTORY was not persisted.', base);
      }

      if (!isValidRedirectUrl(mainUiUrl)) {
        // The write and HISTORY are factual successes; only the return path is unavailable.
        // Do not relabel persisted state as FAILED and do not invent a redirect target.
        return {
          state: 'SYNCED_REDIRECT_UNAVAILABLE',
          stage: 'REDIRECT',
          redirect: null,
          error: { code: 'MAIN_UI_URL_MISSING', message: 'Sync verified but the main ASC UI URL is not configured.' },
          ...base
        };
      }

      return {
        state: 'SYNCED',
        stage: 'REDIRECT',
        redirect: mainUiUrl,
        error: null,
        ...base
      };
    }

    return Object.freeze({ CONFIRM_ACTION, isExplicitConfirmation, previewRequest, confirmAndSyncRequest });
  })(shims.Buffer, shims.atob, shims.btoa, shims.TextEncoder, shims.TextDecoder);
  ASC_RUNTIME_CACHE_ = Object.freeze(ASC_NS);
  return ASC_RUNTIME_CACHE_;
}
