// T-008B — generate apps-script/AscRuntime.gs from the existing owner sources.
//
// The ES-module sources stay the single source of truth. This build only performs a
// mechanical module → namespace wrap so Apps Script V8 can load them:
//   - `import { a, b } from './x.mjs'` → `const { a, b } = <namespace of x>;`
//   - `export function|async function|const` → plain declaration + namespace export
//   - `export { A };` → namespace export
// No semantic code is rewritten. Run with `--check` to fail if the generated file is stale.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const OUTPUT = path.join(HERE, 'AscRuntime.gs');

// Order matters: dependencies first.
export const RUNTIME_MODULES = Object.freeze([
  { file: 'transport/asc-link.mjs', namespace: 'transport' },
  { file: 'transport/envelope-security.mjs', namespace: 'security' },
  { file: 'core/asc-core.mjs', namespace: 'core' },
  { file: 'adapters/github/github-adapter.mjs', namespace: 'githubAdapter' },
  { file: 'adapters/github/github-rest-client.mjs', namespace: 'githubRest' },
  { file: 'ci/zass-ci-status.mjs', namespace: 'zassCi' },
  { file: 'continuity/private-continuity-state.mjs', namespace: 'continuity' },
  { file: 'continuity/index-freshness.mjs', namespace: 'indexFreshness' },
  { file: 'continuity/github-source-head.mjs', namespace: 'sourceHead' },
  { file: 'receipts/write-receipt.mjs', namespace: 'receipts' },
  { file: 'flow/confirm-sync.mjs', namespace: 'flow' }
]);

// History.gs is already Apps Script source; it is included verbatim.
const HISTORY_SOURCE = 'receipts/History.gs';

// Runtime globals the Node sources expect; supplied by RuntimeShims.gs per module scope.
const SHIM_PARAMS = ['Buffer', 'atob', 'btoa', 'TextEncoder', 'TextDecoder'];

function wrapModule(moduleDef, byFile) {
  const absolute = path.join(ROOT, moduleDef.file);
  let source = fs.readFileSync(absolute, 'utf8').replace(/\r\n?/g, '\n');
  const exportsList = [];

  source = source.replace(
    /^import\s*\{([^}]+)\}\s*from\s*'([^']+)';\s*$/gm,
    function (_m, names, spec) {
      const target = path.relative(ROOT, path.resolve(path.dirname(absolute), spec)).split(path.sep).join('/');
      const dep = byFile.get(target);
      if (!dep) {
        throw new Error('Unbundled import ' + spec + ' in ' + moduleDef.file);
      }
      return 'const {' + names + '} = ASC_NS.' + dep.namespace + ';';
    }
  );

  source = source.replace(/^export\s+(async\s+function|function|const)\s+([A-Za-z_$][\w$]*)/gm, function (_m, kind, name) {
    exportsList.push(name);
    return kind + ' ' + name;
  });

  source = source.replace(/^export\s*\{([^}]+)\};\s*$/gm, function (_m, names) {
    names.split(',').map(function (n) { return n.trim(); }).filter(Boolean).forEach(function (n) {
      exportsList.push(n);
    });
    return '';
  });

  if (/^\s*(import|export)\b/m.test(source)) {
    throw new Error('Unsupported module syntax remains in ' + moduleDef.file);
  }

  return [
    '  // ---- module: ' + moduleDef.file + ' ----',
    '  ASC_NS.' + moduleDef.namespace + ' = (function (' + SHIM_PARAMS.join(', ') + ') {',
    "    'use strict';",
    source.split('\n').map(function (line) { return line.length ? '    ' + line : line; }).join('\n'),
    '    return Object.freeze({ ' + exportsList.join(', ') + ' });',
    '  })(' + SHIM_PARAMS.map(function (p) { return 'shims.' + p; }).join(', ') + ');'
  ].join('\n');
}

export function buildRuntime() {
  const byFile = new Map(RUNTIME_MODULES.map(function (m) { return [m.file, m]; }));
  const history = fs.readFileSync(path.join(ROOT, HISTORY_SOURCE), 'utf8').replace(/\r\n?/g, '\n');
  const modules = RUNTIME_MODULES.map(function (m) { return wrapModule(m, byFile); });

  return [
    '// GENERATED by apps-script/build-runtime.mjs — DO NOT EDIT.',
    '// Sources: ' + RUNTIME_MODULES.map(function (m) { return m.file; }).concat([HISTORY_SOURCE]).join(', '),
    '// Regenerate: node apps-script/build-runtime.mjs',
    '',
    '// ==== verbatim: ' + HISTORY_SOURCE + ' ====',
    history.trimEnd(),
    '',
    '// ==== bundled ES modules (lazy, namespaced) ====',
    'var ASC_RUNTIME_CACHE_ = null;',
    '',
    'function ascRuntime_() {',
    '  if (ASC_RUNTIME_CACHE_) {',
    '    return ASC_RUNTIME_CACHE_;',
    '  }',
    '  const shims = ascRuntimeShims_();',
    '  const ASC_NS = {};',
    modules.join('\n\n'),
    '  ASC_RUNTIME_CACHE_ = Object.freeze(ASC_NS);',
    '  return ASC_RUNTIME_CACHE_;',
    '}',
    ''
  ].join('\n');
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const generated = buildRuntime();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
    if (current !== generated) {
      console.error('AscRuntime.gs is stale. Run: node apps-script/build-runtime.mjs');
      process.exit(1);
    }
    console.log('AscRuntime.gs is up to date.');
  } else {
    fs.writeFileSync(OUTPUT, generated);
    console.log('wrote ' + path.relative(ROOT, OUTPUT));
  }
}
